### ISSUE TITLE
Tail_base_sampling sample mode for agent and collector

### ISSUE THREAD

**Issue by JasonChen86899** [jaegertracing/jaeger#2549] opened 2020-10-10 03:07 UTC
## Requirement - what kind of business use case are you trying to solve?
 
This is an introduction about **tail_base_sampling**. [Tail_base_sampling introduction](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/get-started/how-new-relic-distributed-tracing-works#tail-based)
So just try to add  this mode for jaeger agent and collector. Jaeger and jaeger-client need be changed. First make a issue in jaeger

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a new feature

**Comment by yurishkuro** [comment] 2020-10-10 04:20
duplicate of #425

**Closed by yurishkuro** 2020-10-10 04:20 UTC
Labels: duplicate
