### ISSUE TITLE
How to dynamic set Trace sampling strategy?

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/jaeger#1016] opened 2018-08-23 01:58 UTC
Hello, everyone。 I have a question when I was initialized trace configuration, the sampling strategy type was 'const'. How can I reset sampling strategy in agent or collector?

**Comment by yurishkuro** [comment] 2018-08-23 03:35
If the docs (https://www.jaegertracing.io/docs/sampling/) do not explain, please elaborate what is not clear and we can correct them.

**Comment by yurishkuro** [comment] 2018-08-23 03:36
closing as a duplicate of https://github.com/jaegertracing/documentation/issues/125

**Closed by yurishkuro** 2018-08-23 03:36 UTC

**Comment by yurishkuro** [comment] 2018-08-25 02:32
There is no "collector sampling strategy", collectors simply serve the strategies provided via configuration to the clients remotely.  This allows you to change configs, restart collectors, and thus affect the sampling in the clients. We don't support changing sampling strategy in the collectors dynamically via an API call. We do have adaptive sampling though, which will be open sourced soon.
