### ISSUE TITLE
Error reading dependencies from storage: unconfigured table dependencies

### ISSUE THREAD

**Issue by devinbost** [jaegertracing/jaeger#1940] opened 2019-11-22 00:11 UTC
## Requirement
We're attempting to view Dependencies in Jaeger UI. Our Jaeger cluster was configured to integrate with Dgraph with the Cassandra Jaeger backend. The script used to provision the Jaeger keyspace is provided below.

## Problem

We get this error message when we click on the "Dependencies" tab in the UI:
![image](https://user-images.githubusercontent.com/7418031/69386885-2b00ab00-0c81-11ea-948c-34ae331c4718.png)

As a consequence, we cannot view that page. However, we are able to view our Dgraph traces successfully in the Search tab.

## Idea of cause

We're wondering if perhaps something is missing from the Cassandra keyspace that is causing this problem. We used the create.sh script with the v002.cql.tmpl script (that are available here: https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/cassandra/schema ) to generate the keyspace below. 

## Script used to provision Jaeger keyspace in Cassandra:

```
CREATE KEYSPACE IF NOT EXISTS jaeger_v1_prodCluster1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};

CREATE TYPE IF NOT EXISTS jaeger_v1_prodCluster1.keyvalue (
    key             text,
    value_type      text,
    value_string    text,
    value_bool      boolean,
    value_long      bigint,
    value_double    double,
    value_binary    blob,
);

CREATE TYPE IF NOT EXISTS jaeger_v1_prodCluster1.log (
    ts      bigint,
    fields  list<frozen<keyvalue>>,
);

CREATE TYPE IF NOT EXISTS jaeger_v1_prodCluster1.span_ref (
    ref_type        text,
    trace_id        blob,
    span_id         bigint,
);

CREATE TYPE IF NOT EXISTS jaeger_v1_prodCluster1.process (
    service_name    text,
    tags            list<frozen<keyvalue>>,
);

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.traces (
    trace_id        blob,
    span_id         bigint,
    span_hash       bigint,
    parent_id       bigint,
    operation_name  text,
    flags           int,
    start_time      bigint,
    duration        bigint,
    tags            list<frozen<keyvalue>>,
    logs            list<frozen<log>>,
    refs            list<frozen<span_ref>>,
    process         frozen<process>,
    PRIMARY KEY (trace_id, span_id, span_hash)
)
    WITH compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.service_names (
    service_name text,
    PRIMARY KEY (service_name)
)
    WITH compaction = {
        'min_threshold': '4',
        'max_threshold': '32',
        'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.operation_names (
    service_name        text,
    operation_name      text,
    PRIMARY KEY ((service_name), operation_name)
)
    WITH compaction = {
        'min_threshold': '4',
        'max_threshold': '32',
        'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.service_operation_index (
    service_name        text,
    operation_name      text,
    start_time          bigint,
    trace_id            blob,
    PRIMARY KEY ((service_name, operation_name), start_time)
) WITH CLUSTERING ORDER BY (start_time DESC)
    AND compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.service_name_index (
    service_name      text,
    bucket            int,
    start_time        bigint,
    trace_id          blob,
    PRIMARY KEY ((service_name, bucket), start_time)
) WITH CLUSTERING ORDER BY (start_time DESC)
    AND compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.duration_index (
    service_name    text,      // service name
    operation_name  text,      // operation name, or blank for queries without span name
    bucket          timestamp, // time bucket, - the start_time of the given span rounded to an hour
    duration        bigint,    // span duration, in microseconds
    start_time      bigint,
    trace_id        blob,
    PRIMARY KEY ((service_name, operation_name, bucket), duration, start_time, trace_id)
) WITH CLUSTERING ORDER BY (duration DESC, start_time DESC)
    AND compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.tag_index (
    service_name    text,
    tag_key         text,
    tag_value       text,
    start_time      bigint,
    trace_id        blob,
    span_id         bigint,
    PRIMARY KEY ((service_name, tag_key, tag_value), start_time, trace_id, span_id)
)
    WITH CLUSTERING ORDER BY (start_time DESC)
    AND compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 172800
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800;

CREATE TYPE IF NOT EXISTS jaeger_v1_prodCluster1.dependency (
    parent          text,
    child           text,
    call_count      bigint,
    source          text,
);

CREATE TABLE IF NOT EXISTS jaeger_v1_prodCluster1.dependencies_v2 (
    ts_bucket    timestamp,
    ts           timestamp,
    dependencies list<frozen<dependency>>,
    PRIMARY KEY (ts_bucket, ts)
) WITH CLUSTERING ORDER BY (ts DESC)
    AND compaction = {
        'min_threshold': '4',
        'max_threshold': '32',
        'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'
    }
    AND default_time_to_live = 0;
```

**Comment by yurishkuro** [comment] 2019-11-22 00:28
iirc `v002.cql.tmpl` introduced a new table `dependencies_v2`. You must be running the old version of Jaeger that looks for `dependencies` table only.

**Comment by devinbost** [comment] 2019-11-23 05:29
I'm running: 

- jaeger-agent:1.14
- jaeger-collector:1.14
- jaeger-query:1.14

from the available docker containers. 
Are these old versions?

**Comment by yurishkuro** [comment] 2019-11-24 03:10
dependencies_v2 was made the default in v1.11 (#1344). But  the code should still work wit  v1. Please get a more detailed exception from the query service logs.

**Comment by devinbost** [comment] 2019-11-25 17:37
I wasn't seeing logs, so I restarted the docker container for the jaeger-query service and tried to reproduce the issue, and this is what I got:
![image](https://user-images.githubusercontent.com/7418031/69563994-634d0580-0f6f-11ea-9069-cf63a819a70e.png)

I'm not sure what was different from the first case, but it's still concerning that I can't see the dependency graph. Here's what I'm seeing in the logs for the jaeger-query service:

```
2019/11/25 17:22:12 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
{"level":"info","ts":1574702532.2560709,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1574702532.2592008,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1574702532.259329,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":16687}
{"level":"info","ts":1574702532.2593534,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":16687,"health-status":"unavailable"}
{"level":"info","ts":1574702532.3582067,"caller":"cassandra/factory.go:93","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"info","ts":1574702532.393898,"caller":"querysvc/query_service.go:130","msg":"Archive storage not created","reason":"archive storage not configured"}
{"level":"info","ts":1574702532.3939996,"caller":"query/main.go:139","msg":"Archive storage not initialized"}
{"level":"info","ts":1574702532.3947246,"caller":"healthcheck/handler.go:130","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1574702532.3947551,"caller":"app/server.go:135","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1574702532.3947449,"caller":"app/server.go:112","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1574702532.394759,"caller":"app/server.go:125","msg":"Starting GRPC server","port":16686}
```
As you can see, there's not much there.

**Comment by yurishkuro** [comment] 2019-11-25 18:37
are you running the Spark job to generate the dependencies?

**Comment by devinbost** [comment] 2019-11-27 20:36
I'm not... I just ran the Cassandra script to create the Keyspace. Do we need to run a Spark job too?

**Comment by yurishkuro** [comment] 2019-11-27 20:38
Yes. https://www.jaegertracing.io/docs/1.15/deployment/#aggregation-jobs-for-service-dependencies

Still weird that you got that error message, since Spark job doesn't create tables, it only populates the data.

**Comment by sshah90** [comment] 2021-04-21 20:36
Hi @yurishkuro  

is this issue resolved? 

I am seeing the same error in UI although I can see `dependencies_v2` table in Cassandra.

![Screen Shot 2021-04-21 at 4 35 16 PM](https://user-images.githubusercontent.com/26821376/115617598-90fec100-a2bf-11eb-99fb-6c94f2245b8c.png)

Do I have to run Spark job at least one time?

**Info:
Jaeger Version: 1.22.0
Deployed using Jaeger helm chart.**

**Comment by sshah90** [comment] 2021-04-22 15:36
well, I have run spark job still seeing the same issue.

logs from spark job

```
21/04/22 14:33:52 INFO CassandraDependenciesJob: Running Dependencies job for 2021-04-22T00:00Z: 1619049600000000 ≤ Span.timestamp 1619135999999999
21/04/22 14:33:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/04/22 14:34:00 INFO CassandraDependenciesJob: Storing dependencies into dependencies_v2
21/04/22 14:34:01 INFO CassandraDependenciesJob: Done, 8 dependency objects created
```

**Comment by jpkrohling** [comment] 2021-04-23 10:22
@sshah90, are you able to reproduce this error consistently? If so, would you be able to give us the steps?

**Comment by sshah90** [comment] 2021-04-23 13:33
@jpkrohling 

I just deployed it using helm chart and whenever I click on `system architecture` tab, I received errors then I ran spark job still it was the same, then from slack channel, Joe recommended restarting pods which solves the problem for me.

**Comment by allanhung** [comment] 2021-05-12 03:06
I have the same problem when I click on system architecture tab.  I think that might case by [GetDependencyVersion](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/dependencystore/bootstrap.go#L24-L28).  It get V1 when there is no data in dependencies_v2.  After running spark job, it insert data into dependencies_v2.  So the function will get V2 and you need to restart the query pod to take effect.

**Comment by jpkrohling** [comment] 2021-05-12 08:52
@allanhung great find, would you like to contribute with a fix? I think we can invert the logic there: if there's a v1 table, use it, otherwise use v2. 

cc @yurishkuro , @pavolloffay , as you both were active during #1344.

**Comment by yurishkuro** [comment] 2021-05-12 15:24
I think the problem is not with the priority order (v2 already takes priority) but with the fact that the table existence check is only done when the storage factory is instantiated, so after starting the query service it will remember the check and won't repeat it.

**Comment by jpkrohling** [comment] 2021-05-12 16:31
Right, and the idea is that what it remembers is the v2, not v1. So, check for v1 and use it if found, otherwise use v2, which might not exist now but might in the future.

**Comment by yurishkuro** [comment] 2021-05-12 19:10
If the frequency of queries to dependencies is relatively low, then the check for table version can be done at query time instead of at startup time.

**Comment by allanhung** [comment] 2021-05-13 02:07
I test the code, it will return V2 if the dependencies_v2 table exists. No matter there is data in it.  I build a test environment to re-procedure the problem. Here are the steps:
- Install from helm chart
values.yaml
```yaml
cassandra:
  config:
    cluster_size: 3
    seed_size: 2
  persistence:
    enabled: true
    storageClass: cloud-efficiency
    accessMode: ReadWriteOnce
    size: 20Gi

agent:
  enabled: false
```
```bash
helm upgrade --install jqtest \
    --namespace tracing \
    --create-namespace \
    -f values.yaml \
    jaegertracing/jaeger
```
- After it's up and running, scale down cassandra to 1.
```bash
kubectl scale statefulset jqtest-cassandra --replicas=1
```
- restart the jaeger-query pod.
```bash
kubectl rollout restart deploy/jqtest-jaeger-query
```
When jaeger-query issue query `SELECT ts from dependencies_v2 limit 1`, it should get error 'Cannot achieve consistency level LOCAL_ONE' from cassandra. So it will get dependency version with V1.
-  scale cassandra back to 3
```bash
kubectl scale statefulset jqtest-cassandra --replicas=3
```
- browse the ui, you should get 'Error reading dependencies from storage: unconfigured table dependencies'.

In my environment, I enable the cluster-autoscaler.  So there might be chance cassandra and jaeger-query pod need to be migrated to another kubernetes worker node.  And that might cause this issue.

As @yurishkuro mention,  check the table version at query time instead of at startup time is a good idea.

Another workaroud is changing the sql from
`SELECT ts from dependencies_v2 limit 1`
 to
`SELECT count(table_name) FROM system_schema.tables WHERE keyspace_name=? and table_name = 'dependencies_v2'`

**Comment by yurishkuro** [comment] 2024-02-03 20:28
Since this issue only happens with Jaeger versions several years old, I don't think it's worth fixing, closing.

**Closed by yurishkuro** 2024-02-03 20:28 UTC
Labels: storage/cassandra

**Comment by talitz** [comment] 2024-02-26 21:24
<img width="1083" alt="Screenshot 2024-02-26 at 23 23 44" src="https://github.com/jaegertracing/jaeger/assets/15890481/86c3932f-f7b1-46f2-8d05-8cf6e43b5d1b">
Happened to me now, with Jaeger latest chart 1.0.0:
<img width="1691" alt="Screenshot 2024-02-26 at 23 24 19" src="https://github.com/jaegertracing/jaeger/assets/15890481/c40ec45b-ec88-4472-94e7-a803a26fc281">
All pods are up and running.
