### ISSUE TITLE
Fix flaky test TestClientMetricsReporter_Expire

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#2145] opened 2020-03-31 16:52 UTC
```
--- FAIL: TestClientMetricsReporter_Expire (0.02s)
    --- FAIL: TestClientMetricsReporter_Expire/iter0:gauge=1,log=new_client (0.02s)
        client_metrics_test.go:268: 
            	Error Trace:	client_metrics_test.go:268
            	Error:      	Not equal: 
            	            	expected: int(1)
            	            	actual  : int64(0)
            	Test:       	TestClientMetricsReporter_Expire/iter0:gauge=1,log=new_client
    --- PASS: TestClientMetricsReporter_Expire/iter1:gauge=0,log=freeing_stats (0.00s)
FAIL	github.com/jaegertracing/jaeger/cmd/agent/app/reporter	0.064s
```

**Comment by pavolloffay** [comment] 2020-03-31 17:20
It might be a duplicate of https://github.com/jaegertracing/jaeger/issues/2108

**Closed** 2020-03-31 17:21 UTC
Labels: good first issue, help wanted, needs-triage
