### ISSUE TITLE
[Bug]: ES-rollover creates invalid index/alias setup

### ISSUE THREAD

**Issue by kolbitsch-lastline** [jaegertracing/jaeger#4852] opened 2023-10-16 21:07 UTC
### What happened?

When `ingester init $(ES_HOST):443` is executed with env `ES_USE_ALIASES=true`, it creates the first index and configures the write-alias to point at it. As index name, it uses `jaeger-span-000001`.

If the index already exists, merely the write alias is configured accordingly.
If the write alias already exists, no index creation happens.

When ES rollover happens (either via an ES policy or via the `es-rollover` command), a new index is created (e.g., `jaeger-span-000002`) and the write alias is updated to point at the new index.

Then problem arises if the write alias is removed for some reason. `ingester init` will not validate what indices already exist. It will merely validate if `jaeger-span-000001` exists (and skip creating it if it exists already) and point the write alias at it.

If another index already existed at this point (e.g., `jaeger-span-000002`), the write-alias now points to the wrong index. This is not a problem per-se (aside from the fact that ingester now writes to the old index). The problem arises when the next rollover happens: ES will fail to rollover, as it merely takes the index name that the write alias points to, increment the number at the end of the index, create that index, and update the alias.
This fails at the step of index creation, as this index already exists.

Ideally, the `ingester init` should validate what indices exist already and configure the write-alias to point at the last index, so that the next ES-rollover will work as expected.

**Jaeger Ingester Version**
- gitCommit: https://github.com/jaegertracing/jaeger/commit/ee6cc41ef62ba8f04de8a16431b43b620bdf571c
- gitVersion: v1.47.0
- buildDate: 2023-07-06T20:38:11Z

### Steps to reproduce

- run `jaeger-ingester init $(ES_HOST):443`
- perform a rollover. For example using the ES API (but can also be done via `es-rollover`: `POST /jaeger-span-write/_rollover`
- delete ES write alias: `DELETE /jaeger-service-000001/_alias/jaeger-service-write`
- run `jaeger-ingester init $(ES_HOST):443`

### Expected behavior

**Expected behavior:**
- 2 indices exist: `jaeger-service-000001` and `jaeger-service-000002`
- write-alias points at `jaeger-service-000002`
- next ES-rollover will create `jaeger-service-000003` and point write-alias at it

**Actual behavior:**
- 2 indices exist: `jaeger-service-000001` and `jaeger-service-000002`
- write-alias points at `jaeger-service-000001`
- next ES-rollover will fail, because ES will infer next index name to be `jaeger-service-000002` and fail creating this new index. write alias is never updated

### Jaeger backend version

v1.47.0

### Pipeline

Ingester -> Elasticsearch

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes

**Comment by jkowall** [comment] 2024-06-08 21:43
@kolbitsch-lastline Can you explain the use case as to why you are doing this? Specifically, why are you creating the indexes before the rollover and expecting the rollover to work? 

If you do not want rollover, then you should just not use the job and manage it yourself (I have done this before). You are creating a case which shouldn't occur.

**Comment by jkowall** [comment] 2024-06-08 21:45
Dupe of #4851

**Closed by jkowall** 2024-06-08 21:45 UTC
Labels: bug

**Comment by clemenskol** [comment] 2024-06-10 16:00
> @kolbitsch-lastline Can you explain the use case as to why you are doing this? Specifically, why are you creating the indexes before the rollover and expecting the rollover to work?

if ever the alias gets deleted for whatever reason, you end up with an unrecoverable installation. I think my initial description already lays out the steps how to get there

> If you do not want rollover, then you should just not use the job and manage it yourself (I have done this before). You are creating a case which shouldn't occur.

we wanted rollover. We used the job. We had an error in the cluster. We ended up with a broken system. If you think this cannot happen, feel to close as "won't fix", but I was using the documented setup and something messed up the alias (it's been so long, that I unfortunately don't recall the details) and we had to do tons of manual interventions to un-break the setup

**Comment by jkowall** [comment] 2024-06-14 12:30
The suggestion would be to remove the data and start over if you have a data issue. Recreating the alias is not always so straightforward (as you discovered). This issue hasn't really come up before aside from 1-2 times as folks just manage it themselves who need that flexibility. I don't see it as a bug but a feature request for recoverability, but it doesn't seem to have much demand unless someone wants to add that feature. 

Thanks.
