### ISSUE TITLE
How to dynamically change sampler?

### ISSUE THREAD

**Issue by surendarchandra** [jaegertracing/jaeger#1893] opened 2019-11-02 08:09 UTC
## Requirement - what kind of business use case are you trying to solve?

How do I change remote sampler strategy? I'd rather not restart collector so that it can read the sampling file. I was wondering if there was a way to directly inject the sampler into the Trace or 
configure my own web server that services the agent /sampling query. The sampling API implementation on the agent server seems simple enough. Are there helpers to integrated it into my own API service>

## Problem - what in Jaeger blocks you from solving the requirement?
Dynamically change samplers.

**Comment by yurishkuro** [comment] 2019-11-03 21:35
It is currently not implemented. Duplicate of #1058

**Closed by yurishkuro** 2019-11-03 21:35 UTC
