### ISSUE TITLE
duplication of jaeger.tags in child span 

### ISSUE THREAD

**Issue by prana24** [jaegertracing/jaeger#1875] opened 2019-10-23 14:01 UTC
## Requirement - what kind of business use case are you trying to solve?

Trying to add jaeger.tags  as an argument  to jaeger-agent  just to identify  client in multi tenant architecture 

## Problem - what in Jaeger blocks you from solving the requirement?

We see for traces with multiple child span duplicates   tags coming 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Is this a  bug or  we are doing something wrong from our side .  
<img width="910" alt="Capture" src="https://user-images.githubusercontent.com/48326505/67400713-09c27700-f57c-11e9-8ee8-cb08a302d4e4.PNG">

**Comment by prana24** [comment] 2019-10-23 14:07
We are using  jaeger  1.14.1   and grpc    just to add...

**Comment by zoidbergwill** [comment] 2019-10-23 22:14
Sounds like a duplicate of https://github.com/jaegertracing/jaeger/issues/1778

**Closed** 2019-10-24 07:50 UTC
