### ISSUE TITLE
Go spans on port 6832 (Binary Thrift) issue 

### ISSUE THREAD

**Issue by jordo1138** [jaegertracing/jaeger#1594] opened 2019-06-07 20:24 UTC
In running a local build of the HotRod demo app, I'm successful in running the app and having my JAEGER_AGENT_HOST and JAEGER_AGENT_PORT env var's used to send udp spans to my Jaeger agent listening on k8s using Jaeger Operator 1.11 (using jaeger 1.11 docker images)

The spans are sent and received correctly but  I confirmed I only get this error in processing behavior when sending the spans to 6832(Binary Thrift). Sending to 6831 (Compact Thrift) the spans are actually processed and then stored in ES successfully

`{"level":"error","ts":1559936590.2628164,"caller":"processors/thrift_processor.go:116","msg":"Processor failed","error":"Bad version in ReadMessageBegin","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:116"}`

 apps successfully sending spans to this JAEGER_AGENT_HOST and PORT 6832
are all other languages but Go

Any idea on this ? https://github.com/census-instrumentation/opencensus-service/pull/246
and also still an open issue
https://github.com/census-instrumentation/opencensus-service/issues/262

Perhaps need a note somewhere in the docs or even in the HotRod sample to not recommend port 6832 (Binary Thrift) since the go issue still is open

**Comment by yurishkuro** [comment] 2019-06-11 03:23
Jaeger uses different ports for binary and compact Thrift protocols
* https://github.com/jaegertracing/documentation/pull/262
* https://github.com/jaegertracing/jaeger/issues/1596

**Comment by yurishkuro** [comment] 2019-06-11 03:25
Closing, since this is the expected behavior. Opened #1596 to possibly accept both binary & compact protocols on a single port.

**Closed by yurishkuro** 2019-06-11 03:25 UTC
Labels: invalid

**Comment by jordo1138** [comment] 2019-06-11 03:30
That’s fine, I could explain the issue more succinctly in docs to note,
binary not supported by Golang client  differently.

**Comment by yurishkuro** [comment] 2019-06-11 03:32
> binary not supported by Golang client  differently

what do you mean by that?

**Comment by jordo1138** [comment] 2019-06-11 04:00
Yeah so the error I got and posted above cams from setting the hotrod demo app to send spams to binary thrift port which appears to be an issue for Go clients per the other issues I linked to from Opentracing. Was looking for confirmation on that and then perhaps in the docs could note the support or unsupported udp thrift protocols per sdk. Currently the sdk over view has the X or check mark just for UDP and HTTP support
