### ISSUE TITLE
500 error for trace's direct link

### ISSUE THREAD

**Issue by ont** [jaegertracing/jaeger#1008] opened 2018-08-20 16:21 UTC
## Requirement - what kind of business use case are you trying to solve?
Direct links to traces from custom admin panel.

## Problem - what in Jaeger blocks you from solving the requirement?
Some of direct links don't work. Result page contains this info:
```
Status         500
Status text    Internal Server Error
URL            /api/traces/14eb328dd1b13df
Response body  
{
  "data": null,
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": [
    {
      "code": 500,
      "msg": "No trace with that ID found"
    }
  ]
}
```
**But** search query to `/api/traces/?start=...` is fine. Jaeger's web ui also can find this traces and even open them, but after page refreshing I get 500 error.

## Additional info

1. Probably there are no errors for this 500 error in logs from `jaeger-query`
2. `latest` version of docker container for `jaeger-query` and `1.6` for `jaeger-agent` and `jaeger-collector`

## Update
It seems that all traces which was created more than 2 days ago returns 500 errors for their direct links.
Does jaeger has some internal time filter?

**Comment by code98** [comment] 2019-02-25 11:48
me too

**Comment by black-adder** [comment] 2019-02-25 15:58
Where are you storing your traces? [Cassandra](https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/create.sh#L21) has a default TTL of 2 days.

**Comment by ont** [comment] 2019-02-25 19:15
I store traces in elasticsearch. They are not deleted, I can access them via `/api/traces` search api call.
The problem is that jaeger's web ui is able to show such traces (probably 2 day old) only from search list and not via direct links.

**Comment by yurishkuro** [comment] 2019-02-25 19:31
@pavolloffay I am guessing this is because query-service formulates the list of indices to loop through based on the lookup window parameter. With rollover & alias approach this probably wouldn't be an issue.

@ont are  you setting this parameter in query-service to match your TTL?

```
      --es.max-span-age duration                           The maximum lookback for spans in ElasticSearch (default 72h0m0s)
```

**Comment by ont** [comment] 2019-02-25 19:36
No, I set the only `--es.server-urls` parameter for `jaeger-query` service.

**Comment by disider** [comment] 2019-04-09 07:37
We have the same issue.

**Comment by yurishkuro** [comment] 2019-04-09 17:29
As I mentioned in https://github.com/jaegertracing/jaeger/issues/1008#issuecomment-467149540, `--es.max-span-age` controls how fart back ES storage looks for spans (default 72hrs).

**Comment by beoboo** [comment] 2019-04-09 19:53
But if we don't set it, it should keep the default, and we noticed the same before even for spans generated "a few seconds ago".

**Comment by disider** [comment] 2019-04-09 19:55
But if we don't set it, it should keep the default, and we noticed the same before even for spans generated "a few seconds ago".

**Comment by pavolloffay** [comment] 2019-04-10 08:33
This seems like a bug, the trace should not be found via `/api/traces/?start` if the direct link `/api/traces/14eb328dd1b13df` does not work.

Both APIs should be using the same list of indices for search.

The find traces uses end time from query paramters and not max span age:
` FindTraces(ctx context.Context, traceQuery *spanstore.TraceQueryParameters) ` uses `return s.multiRead(ctx, uniqueTraceIDs, traceQuery.StartTimeMin, traceQuery.StartTimeMax)` whereas `GetTrace(ctx context.Context, traceID model.TraceID)` `s.multiRead(ctx, []model.TraceID{traceID}, currentTime.Add(-s.maxSpanAge), currentTime)`

**Comment by pavolloffay** [comment] 2019-04-10 08:36
The fix might be related to https://github.com/jaegertracing/jaeger/issues/1361. We could use time range queries and simply go through all indices (pass regex into index name). ES should do some optimizations to find correct indices.

**Comment by pavolloffay** [comment] 2019-06-21 13:13
I will close this as this behavior is enforced by design and controlled by `--es.max-span-age` parameter. To store historical traces use archive storage.

**Closed by pavolloffay** 2019-06-21 13:13 UTC
Labels: elasticsearch
