### ISSUE TITLE
Elasticsearch Storage Backend Failed to create index

### ISSUE THREAD

**Issue by cheveyo20** [jaegertracing/jaeger#658] opened 2018-01-19 11:14 UTC
Hi,

this is a part of my docker-compose file. I am running an elasticsearch with 3 nodes:

```  
 jaegertracing-collector:
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    networks:
      - default
    image: jaegertracing/jaeger-collector
    entrypoint: /go/bin/collector-linux --es.server-urls=http://10.11.47.55:9200,http://10.11.47.56:9200,http://10.11.47.57:9200 --span-storage.type=elasticsearch --log-level=debug

  jaegertracing-agent:
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    networks:
      - default
    image: jaegertracing/jaeger-agent
    entrypoint: /go/bin/agent-linux --collector.host-port=jaegertracing-collector:14267

  jaegertracing-query:
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    networks:
      - default
    ports:
      - "16686:16686"
    image: jaegertracing/jaeger-query
    entrypoint: /go/bin/query-linux --es.server-urls=http://10.11.47.55:9200,http://10.11.47.56:9200,http://10.11.47.57:9200 --span-storage.type=elasticsearch --log-level=debug --query.static-files=/go/jaeger-u$

```

The jaeger collector is throwing the following error:
```
":"error","ts":1516358331.2152708,"caller":"app/span_processor.go:103","msg":"Failed to save span","error":"Failed to create index: elastic: Error 400 (Bad Request): [logs] is defined as an object in mapping [span] but this name is already used for a field in other types [type=illegal_argument_exception]","errorVerbose":"elastic: Error 400 (Bad Request): [logs] is defined as an object in mapping [span] but this name is already used for a field in other types [type=illegal_argument_exception]\nFailed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:194\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:150\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:127\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:103\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
{"level":"error","ts":1516358331.373291,"caller":"spanstore/writer.go:193","msg":"Failed to create index","trace_id":"ec19dddfb067d0ce","span_id":"ec19dddfb067d0ce","error":"elastic: Error 400 (Bad Request): [logs] is defined as an object in mapping [span] but this name is already used for a field in other types [type=illegal_argument_exception]","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:193\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:150\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:127\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
```

**Comment by pavolloffay** [comment] 2018-01-19 13:43
@cheveyo20 do you store something else to ES?

**Comment by pavolloffay** [comment] 2018-01-19 14:52
Can you share compose file with ES definitions?

**Comment by cheveyo20** [comment] 2018-01-19 14:55
The Elasticsearch is not running containerized, its deployed via ansible on 3 nodes:

```
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 6,
  "active_shards" : 12,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

**Comment by cheveyo20** [comment] 2018-01-26 12:20
Any idea, how i can solve it? 
Do i need to create the index manually? Or execute some installation script?
I am using ElasticSearch Version 5.6.3

grretings CheVeyo

**Comment by pavolloffay** [comment] 2018-01-26 13:17
How many instances of jaeger-collector are you running? 

Can you share the ansible script to deploy ES?

**Comment by cheveyo20** [comment] 2018-01-26 13:28
I am running one jaeger-collector it is deployed via docker swarm (see on top of the page)

Ansible Playbook:

```
---
- name: Elasticsearch Cluster
  hosts: elasticsearch-master
  roles:
    - { role: elasticsearch, es_instance_name: "{{ ansible_hostname }}", es_heap_size: "12g",
    es_config: {
        cluster.name: "elasticsearch",
        discovery.zen.ping.unicast.hosts: "{{ elasticsearch_nodes }}",
        discovery.zen.minimum_master_nodes: 2,
        http.port: 9200,
        transport.tcp.port: 9300,
        network.host: 0.0.0.0,
        node.data: true,
        node.master: true,
        bootstrap.memory_lock: false,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- name: Kibana
  hosts: kibana-nodes
  roles:
    - {role: kibana}
```
the role elasticsearch is directly mapped to the offical elasticsearch role:

https://github.com/elastic/ansible-elasticsearch

**Comment by cheveyo20** [comment] 2018-02-05 11:07
Do i need to prepare the elasticsearch in any way?

**Comment by pavolloffay** [comment] 2018-02-05 13:50
No configuration is required. Still the same error?

**Comment by pavolloffay** [comment] 2018-02-06 09:26
@cheveyo20 can you please confirm Jaeger version you are using? It's a version command `jaeger-binary version`

**Comment by japgolly** [comment] 2018-02-06 10:23
I've also seen this error using ES 6.1.2 and Jaeger 1.1.0.

**Comment by pavolloffay** [comment] 2018-02-06 10:31
@japgolly note that ES 6.x is not supported at the moment.

**Comment by cheveyo20** [comment] 2018-02-07 13:59
Ok i could solve it with downgrading to Elasticsearch 5.2.1
It seems that 5.6.3 is conflicting with the collector

**Comment by danielbenzvi** [comment] 2018-05-02 09:49
is there any solution for this? we're using 5.6.3 as well and jaeger is failing to create the index.

**Comment by pavolloffay** [comment] 2018-05-02 10:28
@danielbenzvi I wasn't able to reproduce this issue. Would it be possible to share a reproducer?

**Comment by jpkrohling** [comment] 2019-04-02 14:25
@kevinearls do you want to try to reproduce this one? Looks like different people are affected.

**Comment by kevinearls** [comment] 2019-04-02 15:56
@jpkrohling  Sure, I can try.

**Comment by pavolloffay** [comment] 2019-06-21 14:12
@danielbenzvi @cheveyo20 @japgolly were you able to solve this problem? I was not able to reproduce this locally. I will close this as it is quite old and probably related to user environment. Please comment if the issue is still there.

Based on the log message from the first comment I guess ES contained span type in other indexes

```":"error","ts":1516358331.2152708,"caller":"app/span_processor.go:103","msg":"Failed to save span","error":"Failed to create index: elastic: Error 400 (Bad Request): [logs] is defined as an object in mapping [span] but this name is already used for a field in other types [type=illegal_argument_exception]","errorVerbose":"elastic: Error 400 (Bad Request): [logs] is defined as an object in mapping [span] but this name is already used for a field in other types
```

**Closed by pavolloffay** 2019-06-21 14:12 UTC
Labels: elasticsearch
