### ISSUE TITLE
Converting JSONSpan to domain Span failed: encoding/hex: invalid byte: U+002E '.'

### ISSUE THREAD

**Issue by hyhanyan** [jaegertracing/jaeger#1926] opened 2019-11-15 11:13 UTC

**Comment by hyhanyan** [comment] 2019-11-15 11:14
use jaeger-ui , 
![image](https://user-images.githubusercontent.com/11550403/68939703-22980400-0799-11ea-9d76-a2578723625c.png)

**Comment by yurishkuro** [comment] 2019-11-15 19:30
I am assuming you're using Elasticsearch?  Since it's the only storage that uses JSON as representation.

There may be data corruption in the storage, or a bug in the write path. I'd recommend looking in the storage for what kind of data is stored. Hex encoding would be used for trace/span IDs.

**Comment by yurishkuro** [comment] 2019-11-15 19:30
cc @pavolloffay

**Comment by hyhanyan** [comment] 2019-11-18 02:59
@yurishkuro Thanks, I will try it

**Comment by hyhanyan** [comment] 2019-11-18 02:59
@yurishkuro Thanks, I will try it

**Comment by pavolloffay** [comment] 2019-11-29 17:39
@hyhanyan could you please provide a reproducer? 

The best would be to read the data from ES index directly e.g. `curl http://localhost:9200/jaeger-span*/_search?`

and try to post here segment which is causing the issue.

**Comment by pavolloffay** [comment] 2019-12-04 13:44
Closing in favor of #1960

**Closed by pavolloffay** 2019-12-04 13:44 UTC
Labels: bug, elasticsearch
