### ISSUE TITLE
When span time is small (e.g., less than 1s), discard the span and do not display the span in the trace

### ISSUE THREAD

**Issue by yzpangu** [jaegertracing/jaeger#1552] opened 2019-05-20 06:46 UTC
When span time is small (e.g., less than 1s), discard the span and do not display the span in the trace

**Comment by yzpangu** [comment] 2019-05-20 06:46
How can I do that

**Comment by yurishkuro** [comment] 2019-05-20 14:43
Jaeger does not support that. If you like to propose an enhancement, please describe business requirement / user story (this was asked in the issue template, btw).

**Comment by yzpangu** [comment] 2019-05-21 02:29
When jaeger was used in our project, it produced a lot of spans, and we wanted to reduce the number of spans. So we want to remove the low time consuming span from the traces, such as the [mysql select] span, except for the high time consuming span we want to keep

**Comment by black-adder** [comment] 2019-05-21 14:53
@tiffon @everett980 this would be a pretty nice filter to have on the UI.

**Comment by yurishkuro** [comment] 2019-05-21 19:23
@yzpangu have you tried expand/collapse functionality in the UI?  It allows you to focus on important spans already.

**Comment by yzpangu** [comment] 2019-05-22 02:03
I mean it's not just no need shown on the UI, it's not stored. These low time consuming spans don't make much sense to us, and storage costs are high.I want discard it when  span time is small，no stored

**Comment by yurishkuro** [comment] 2019-05-22 02:34
In the current architecture it is not easy to suppress the storage of such spans. Each span records a reference to its parent, so if you have a chain  A->B->C and span B meets your criteria of being "too short", if we simply drop it then span C will  become orphaned and the UI will have to show it as the top-level span. To be able to cleanly exclude certain spans from the graph you first need to collect the full trace.

We have some plans to look  into pre-aggregating traces before storing (because that would  allow batched writes, which are more efficient in Cassandra), but I can't give any timeline of when this will be implemented.

**Comment by yzpangu** [comment] 2019-05-22 03:56
I see. Thank you

**Comment by jpkrohling** [comment] 2019-05-24 15:13
> We have some plans to look into pre-aggregating traces before storing

How do you determine that a trace is "done" ?

**Comment by yurishkuro** [comment] 2019-05-27 03:05
for the purpose of storage it's not necessary to know if the trace is "done", since it's just a performance optimization.

**Comment by wuyupengwoaini** [comment] 2019-05-28 03:02
@yzpangu  I suppose that you only need to customize the Reporter interface to meet your needs.But it only can meet your part of needs because of the reasons mentioned  above by @yurishkuro .

e.g. If the span has no child span like [mysql select] span,you can customize reporter.

`
import io.jaegertracing.internal.JaegerSpan;
import io.jaegertracing.spi.Reporter;
import io.opentracing.tag.Tags;

import java.util.Map;

/**
 * @Description
 * @Author wuyupeng
 * @Date 2019/5/28 10:57
 **/
public class MySqlCustomeizeReporter implements Reporter {
    private Reporter realReporter;

    private int minDuration;

    public MySqlCustomeizeReporter(Reporter realReporter, int minDuration) {
        this.realReporter = realReporter;
        this.minDuration = minDuration;
    }

    @Override
    public void report(JaegerSpan span) {
        if (!isDBSpan(span) || span.getDuration() < minDuration) {
            realReporter.report(span);
        }
    }

    private boolean isDBSpan(JaegerSpan span) {
        Map<String, Object> tags = span.getTags();
        if (tags == null || tags.size() == 0) {
            return false;
        }
        String dbStatement = (String) tags.get(Tags.DB_STATEMENT);
        return dbStatement != null && dbStatement.length() > 0;
    }

    @Override
    public void close() {
        realReporter.close();
    }
}
`

**Comment by yzpangu** [comment] 2019-06-02 11:09
@yurishkuro  maybe jaeger should support customize the Reporter interface and Sampler interface, as @wuyupengwoaini said. make it More scalable
```java

import com.yunzong.taoist.common.customize.reporter.MyReporter;
import io.jaegertracing.Configuration;
import io.jaegertracing.internal.JaegerTracer;
import io.jaegertracing.spi.Reporter;

public class MyConfiguration extends Configuration{

	public MyConfiguration(String serviceName) {
		super(serviceName);
		// TODO Auto-generated constructor stub
	}

	@Override
	public JaegerTracer.Builder getTracerBuilder() {
		JaegerTracer.Builder builder = super.getTracerBuilder();
		Reporter realReporter = builder.getReporter(); // The parent class does not define this method,  I defined and recompile the jar
		MyReporter reporter = new MyReporter(realReporter,20);
		builder.withReporter(reporter);
		return builder;
	}
}
```

**Comment by quaff** [comment] 2019-06-26 01:55
Here is my solution
```
import java.util.function.Predicate;

import io.jaegertracing.internal.JaegerSpan;
import io.jaegertracing.spi.Reporter;
import io.opentracing.tag.Tags;

public class DelegatingReporter implements Reporter {

	private final Reporter delegate;

	private final Predicate<JaegerSpan> predicate;

	public DelegatingReporter(Reporter delegate, Predicate<JaegerSpan> predicate) {
		this.delegate = delegate;
		this.predicate = predicate;
	}

	@Override
	public void report(JaegerSpan span) {
		if (span.context().isDebug() || Boolean.TRUE.equals(span.getTags().get(Tags.ERROR.getKey()))
				|| span.getTags().get(Tags.SAMPLING_PRIORITY.getKey()) != null || span.getTags().get("async") != null
				|| predicate.test(span))
			delegate.report(span);
	}

	@Override
	public void close() {
		delegate.close();
	}

}

```
```
Reporter reporter = new RemoteReporter.Builder().withSender(sender).build();
reporter = new DelegatingReporter(reporter, span -> span.getDuration() >= 5 * 1000);
```

**Comment by yurishkuro** [comment] 2019-07-04 17:56
@quaff your solution can easily lead to broken traces, per my earlier https://github.com/jaegertracing/jaeger/issues/1552#issuecomment-494629024

**Comment by quaff** [comment] 2019-07-05 00:27
@yurishkuro I realize that, so I add some tag conditions to mitigate it.

**Comment by yurishkuro** [comment] 2021-01-10 20:55
now duplicate of https://github.com/jaegertracing/jaeger-ui/issues/435

**Closed by yurishkuro** 2021-01-10 20:55 UTC
Labels: enhancement
