### ISSUE TITLE
Strange indices names in ES

### ISSUE THREAD

**Issue by ybychenok** [jaegertracing/jaeger#1804] opened 2019-09-18 08:33 UTC
I have a strange situation with my Jaeger Elasticsearch setup. After listing all ES indexes I see next picture:
```
# curl -s -XGET 'http://localhost:9200/_cat/indices?v'
...
green  open   jaeger-service-18403-09-26      K585jgOASWKjKPSMbRn7FA   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-service-14286-12-03      3_o_-KyJS8m8rmoKYDsX7g   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-service-14072-09-22      n6KpLxcoQfCbuTCHEcnq0g   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-span-27633-07-05         SM3Lm5agSbOA7urq_h3wLg   5   1          0            0      2.3kb          1.2kb
green  open   jaeger-span-14074-08-19         __ZVDwtKSS2lvHy1J_h1Dw   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-service-12864-07-22      0e8C0GqMSoOSjhR8NeXYRA   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-service-11936-02-07      Ll-Co7A6QYeD0M5AbfRSZQ   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-service-12866-01-24      vC0ntR5IR5yU-TivFbFsOw   5   1          0            0      2.5kb          1.2kb
green  open   jaeger-span-11926-02-05         6d23haSkS5KbJsEIYjWLZw   5   1         80            0     79.8kb         39.9kb
...
```
So there are a lot of such indexes with a very small size, near 1-50 KBs and the amount of them is very big (~1000-10000). It's critical for Elasticsearch's health to have such many indexes. I suppose that only one correct name of such indexes is `jaeger-span-YY-MM-DD`.

Maybe I am doing something wrong? Could you help somehow or link me to a some helpful url? Thanks.

PS. ES v.6.3.1, jaeger-collector/query v1.13.1, Amazon Linux AMI 2018.03, Docker version 18.06.1-ce (ES and jaeger is working in Docker).

**Comment by pavolloffay** [comment] 2019-09-18 08:39
The date in indices is  span start time from incoming data. So it seems you the instrumentation is submitting data with a wrong timestamps, perhaps the time on your machines is not correctly configured. 

The related issue is https://github.com/jaegertracing/jaeger/issues/841

**Comment by ybychenok** [comment] 2019-09-18 09:30
@pavolloffay thanks. At least I know why that occurs.

**Comment by pavolloffay** [comment] 2019-09-18 09:43
it would be great to hear why it happens in your system. If it is by accident or you have to use different times. 

I will close this issue as it is a duplicate of #841. Feel free to continue commenting.

**Closed by pavolloffay** 2019-09-18 09:43 UTC
Labels: elasticsearch
