### ISSUE TITLE
Getting spans from PHP client to the collectors (was: skipping clock skew adjustment)

### ISSUE THREAD

**Issue by jukylin** [jaegertracing/jaeger#477] opened 2017-10-18 06:31 UTC
Hi,I released jaeger and [jaeger-php](https://github.com/jukylin/jaeger-php) to Pro Env. But I Got warnings:
`
invalid parent span IDs=54a22ef518e5263; skipping clock skew adjustment
`
This is because of  UDP packet loss?

**Comment by black-adder** [comment] 2017-10-18 14:19
Looks like the parent span is missing during clock skew adjustment. It might be due to UDP packet loss but it could also be because the parent span was never reported or the instrumentation is wrong.

**Comment by jukylin** [comment] 2017-10-19 02:18
Thinks,Mybe that problem is not with the UDP packet loss.
Wo found more errors in jaeger-collector:
```
"caller":"spanstore/writer.go:180","msg":"Failed to create index",
"trace_id":"bca566c1ebb9b93","span_id":"4f8a8ec0887eb93",
"error":"elastic: Error 400 (Bad Request):
 index [jaeger-service-2017-10-18/LcHvUOGxSAmf5gAI-26S1g] already exists
```
Es not good for write operations.

**Comment by jukylin** [comment] 2017-10-24 02:07
I Get this In Metrics Backends:
```
jaeger_agent.thrift.udp.t-processor.handler-errors.model_zipkin.protocol_compact:35563
```
https://github.com/jaegertracing/jaeger/blob/master/cmd/agent/app/processors/thrift_processor.go#L112

Handle Thrift Data error.

The same  problem for the [hotrod](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod), when I run
```
ab -c 10 -n 1000 http://127.0.0.1:8080/dispatch?customer=123\&nonse=0.09988063950724668
```

error logs 
```
{"level":"info","ts":1508777261.1863217,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.BinaryAnnotation error reading struct: error reading field 1: Invalid data length"}
{"level":"info","ts":1508777344.1827667,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.Span field 37 read error: don't know what type: %!s(thrift.tCompactType=14)"}
{"level":"info","ts":1508777347.1794112,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.Annotation error reading struct: *zipkincore.Endpoint error reading struct: error reading field 1: EOF"}
{"level":"info","ts":1508777360.1809387,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.Annotation error reading struct: Invalid data length"}
{"level":"info","ts":1508777364.181556,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.Annotation error reading struct: *zipkincore.Annotation field 13 read error: don't know what type: %!s(thrift.tCompactType=15)"}
{"level":"info","ts":1508777370.1790407,"caller":"processors/thrift_processor.go:114","msg":"processBuffer*zipkincore.Span error reading struct: *zipkincore.Annotation error reading struct: *zipkincore.Endpoint error reading struct: Invalid data length"}
```

It looks strange, why did these problems arise.

**Comment by black-adder** [comment] 2017-10-24 03:59
Instead of emitting zipkin model from the php client, can you emit jaeger instead? It looks like there's some conversion errors for zipkin

**Comment by jukylin** [comment] 2017-10-24 14:40
change port 5775 => 6831 ?

**Comment by black-adder** [comment] 2017-10-24 15:18
yup, send jaeger thrift to agent port 6831 from the php client

**Comment by jukylin** [comment] 2017-10-24 15:58
It not work with hotrod. I set Reporter. LocalAgentHostPort : 0.0.0.0:6831

> https://github.com/jaegertracing/jaeger/blob/master/examples/hotrod/pkg/tracing/init.go#L31
```
cfg := config.Configuration{
	Sampler: &config.SamplerConfig{
		Type:  "ratelimiting",
		Param: 1,
	},
	Reporter: &config.ReporterConfig{
		LogSpans:            false,
		BufferFlushInterval: 1 * time.Second,
		LocalAgentHostPort:"0.0.0.0:6831",
	},
}
```
Result :
> jaeger_agent.thrift.udp.t-processor.handler-errors.model_jaeger.protocol_compact : 10

**Comment by black-adder** [comment] 2017-10-24 16:28
hotrod already defaults to 6831 so that's not necessary. Good to know it works with php

**Comment by jukylin** [comment] 2017-10-25 02:10
I got the new code, the problem still exists in hotrod.
I run : 
```
ab -c 10 -n 1000 http://127.0.0.1:8080/dispatch?customer=123\&nonse=0.09988063950724668
```
Result:
```
jaeger_agent.thrift.udp.server.packets.processed.model_jaeger.protocol_compact:1765
jaeger_agent.thrift.udp.t-processor.handler-errors.model_jaeger.protocol_compact:21
```

And, In test Pro ,I set port to 6831 in php client.The problem exists too.
```
jaeger_agent.thrift.udp.server.packets.processed.model_jaeger.protocol_compact:41103
jaeger_agent.thrift.udp.t-processor.handler-errors.model_jaeger.protocol_compact:723
```

**Comment by jukylin** [comment] 2017-10-27 10:05
To help mitigate the problem, We adjust the sampling strategy.

**Comment by yurishkuro** [comment] 2017-10-27 12:11
@jukylin it appears your thrift payload is malformed. How does sampling help with that?

**Comment by jukylin** [comment] 2017-10-27 12:40
The problem still exists,just the number of appearances is less. In the beginning we used ConstSampler, now we using ProbabilisticSampler( probability 0.1)

**Comment by frankgreco** [comment] 2017-11-14 00:39
I am also seeing this issue. I can't directly correlate it but it seems like this might have started to happen when I limited the amount of memory the _all in one_ Kubernetes pod received (I set it to 3GB). Could this be a side effect if available memory starts to become an issue?

**Comment by yurishkuro** [comment] 2017-12-23 19:16
@jukylin what is the state of this issue?  The title does not reflect the discussion, which was around getting spans from PHP client to the collectors.

**Comment by wuyupengwoaini** [comment] 2019-03-21 06:54
We also meet the same problem,but We use the offical  jaeger-client-python.
{"level":"error","ts":1553147300.620123,"caller":"processors/thrift_processor.go:116","msg":"Processor failed","error":"*jaeger.Batch error reading struct: *jaeger.Span error reading struct: *jaeger.Tag error reading struct: don't know what type: %!s(thrift.tCompactType=13)","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:116"}

**Comment by jpkrohling** [comment] 2019-04-02 13:40
@wuyupengwoaini are you able to provide a reproducer?

**Comment by wuyupengwoaini** [comment] 2019-04-03 06:55
@jpkrohling  This error happens by chance, as if only certain data will cause the error. So I don't know how to reproduce this error.

**Comment by jpkrohling** [comment] 2019-04-03 09:44
I just tried hitting Hot ROD with the `ab` command shown before, with different concurrency levels (10, 100) and couldn't reproduce this on master, either with the default reporter type (`grpc`) nor with `tchannel` (which would probably be the only one affected by this). 

Here's what I tried:
```console
$ go run ./cmd/all-in-one/main.go --reporter.type=tchannel --reporter.tchannel.host-port=127.0.0.1:14267
$ go run ./examples/hotrod/main.go all
$ ab -c 100 -n 5000 http://127.0.0.1:8080/dispatch?customer=123\&nonse=0.09988063950724668
```

Right now, we don't have actionable information to fix this problem. Given that we are phasing out `tchannel` anyway, I'll close this one but feel free to reopen if this can be reproduced or if you have further information that would help us identify the problem.

**Closed by jpkrohling** 2019-04-03 09:44 UTC
Labels: bug

**Comment by boekkooi-fresh** [comment] 2019-11-25 14:19
In regard to `Processor failed","error":"*jaeger.Batch error reading struct: *jaeger.Span error reading struct: *jaeger.Tag error reading struct: error reading field 3: Invalid data length`
When I have encountered this it has been a issue with a tag value (span attribute value) being to large. I assume this causes the maximum UDP packet size to be hit but I maybe wrong.
