### ISSUE TITLE
[Feature]: Add optional time window when fetching trace by id using grpc-plugin

### ISSUE THREAD

**Issue by rim99** [jaegertracing/jaeger#6123] opened 2024-10-26 03:17 UTC
### Requirement

We are using Jaeger UI to explore traces managed by Grafana Tempo.

Jaeger query uses GRPC plugin to send requrest to Tempo cluster.

### Problem

Although currently this thing works, Jaeger cannot send optional time window to hint Tempo to query limited blocks from S3

### Proposal

I would suggest to add optional time window (start & end timestamp) in GRPC storage plugin proto file: https://github.com/jaegertracing/jaeger/blob/85d558dff128feb767f7d5b9c70e3683745ecc9c/plugin/storage/grpc/proto/storage.proto#L69

Different backends can decide how to use it.

**Comment by yurishkuro** [comment] 2024-10-27 04:56
Duplicate of #4150

**Closed by yurishkuro** 2024-10-27 04:56 UTC
Labels: enhancement, area/storage
