### ISSUE TITLE
#coop-mode for jaeger

### ISSUE THREAD

**Issue by hh** [jaegertracing/jaeger#5285] opened 2024-03-20 14:02 UTC
Met with @jkowall at Paris Kubecon.
Going to try to setup a gist for creating a jaeger onboarding.

Tracking issue.

**Comment by varshith257** [comment] 2024-03-20 14:07
@hh The issue isn't clear and can't get what you are intending.Please fill detailed issue

**Comment by jkowall** [comment] 2024-03-20 14:13
@varshith257 I am handling this one in person tomorrow with him at Kubecon, he just wanted a tracking issue. I have updated/assigned it. Thank you.

**Comment by manishramanandi** [comment] 2024-10-02 08:57
hey can i contribute?

**Comment by yurishkuro** [comment] 2024-10-02 13:58
@jkowall what is this about? There is no context.

**Closed** 2024-10-02 15:10 UTC
Labels: documentation
