### ISSUE TITLE
[Bug]: Ingester does not fail on Elasticsearch storage failure

### ISSUE THREAD

**Issue by kolbitsch-lastline** [jaegertracing/jaeger#4851] opened 2023-10-16 20:52 UTC
### What happened?

**Our scenario:**
- We use Elasticsearch (or, more precisely AWS OpenSearch) for storing spans.
- Spans are read from a Kafka topic (written by our data collector).
- We use `jaeger-ingester` for reading data from Kafka and writing into Elasticsearch.
- We use `jaeger-es-rollover init` to bootstrap ES by creating the needed indices as well as configuring the write alias for ingestion. The initialization happens as K8s init-container prior to the "main" container running ingester.
- We use `jaeger-es-rollover` to periodically create new indices (when the index gets too old or large) and to update the write index.
- We configure ES to not allow automatic creation of indices. This is to enforce that indices are created correctly and that a write alias is put in place prior to writing to the index. Some details on this (unrelated to the actual bug): this is done to avoid ingester creating misnamed indices in case the write alias is removed. We found that if a faulty policy removes the write-alias, ingester (or actually Elasticsearch) would auto-create an index using the name of the write-alias. This would, in turn, break the es-rollover in a later step, as the index and alias were misconfigured.

**The problem:**
When the write alias becomes misconfigured (or non-existent) after the init-container has completed, we found that jaeger-ingester does not fail. Instead, it logs that the process is unable to write to ES and continues. For example

```
ingester-8474c6b5c-gkxlr jaeger-ingester {"level":"error","ts":1697481974.4077141,"caller":"config/config.go:129","msg":"Elasticsearch part of bulk request failed","map-key":"index","response":{"_index":"jaeger-span-write","_type":"_doc","status":404,"error":{"type":"index_not_found_exception","reason":"no such index [jaeger-span-write]","resource.type":"index_expression","resource.id":"jaeger-span-write","index":"jaeger-span-write"}},"stacktrace":"github.com/jaegertracing/jaeger/pkg/es/config.NewClient.func2\n\tgithub.com/jaegertracing/jaeger/pkg/es/config/config.go:129\ngithub.com/olivere/elastic.(*bulkWorker).commit\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:588\ngithub.com/olivere/elastic.(*bulkWorker).work\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:501"}
```

Because the ingester does not terminate on error, the init-container is never re-executed, which would configure indices and the write alias.

**Expected behavior:**
When ingester fails to write to ES, the process should not only log the error but also crash. Messages read from Kafka should not be ACK'ed. K8s can restart

**Jaeger Ingester Version**
- gitCommit: ee6cc41ef62ba8f04de8a16431b43b620bdf571c
- gitVersion: v1.47.0
- buildDate: 2023-07-06T20:38:11Z

### Steps to reproduce

- configure ES and mark the cluster to not auto-create indices:

```
PUT /_cluster/settings
{
  "persistent": {
    "action.auto_create_index": "false"
  }
}
```

- run `jaeger-es-rollover init $(ES_HOST):443`
- run `jaeger-ingester` with env `ES_USE_ALIASES=true`
- delete ES write alias:

```
DELETE /jaeger-service-000001/_alias/jaeger-service-write
```

- send data to ingester

### Expected behavior

Expected behavior: ingester logs error and stops
Actual behavior: ingester logs error and continues execution

### Relevant log output

```shell
ingester-8474c6b5c-gkxlr jaeger-ingester {"level":"error","ts":1697481974.4077141,"caller":"config/config.go:129","msg":"Elasticsearch part of bulk request failed","map-key":"index","response":{"_index":"jaeger-span-write","_type":"_doc","status":404,"error":{"type":"index_not_found_exception","reason":"no such index [jaeger-span-write]","resource.type":"index_expression","resource.id":"jaeger-span-write","index":"jaeger-span-write"}},"stacktrace":"github.com/jaegertracing/jaeger/pkg/es/config.NewClient.func2\n\tgithub.com/jaegertracing/jaeger/pkg/es/config/config.go:129\ngithub.com/olivere/elastic.(*bulkWorker).commit\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:588\ngithub.com/olivere/elastic.(*bulkWorker).work\n\tgithub.com/olivere/elastic@v6.2.37+incompatible/bulk_processor.go:501"}
```
```


### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v1.47.0

### SDK

_No response_

### Pipeline

OTEL SDK -> OTEL Collector -> Kafka -> Jaeger ingester -> Elasticsearch/OpenSearch

### Stogage backend

OpenSearch 7

### Operating system

Linux (k8s node/k8s pod/container)

### Deployment model

Kubernetes

### Deployment configs

_No response_

**Comment by yurishkuro** [comment] 2023-10-16 21:12
> We use jaeger-ingester "init" to bootstrap ES

I don't follow - do you mean you use some k8s trickery to execute another container? There's no "init" in the ingester.

> When the write alias becomes misconfigured (or non-existent) after the init-container has completed

What is the root cause of that failure?

Jaeger components are generally not designed to die when they encounter an error from a storage backend, only when they cannot connect to it in the first place during startup. What you're describing is not a bug, but as-designed behavior.

There is a question to be asked if ingester should recognize "index does not exist" error somehow and then die, because clearly it would never be successful writing data until the index is created. I feel like this is an edge case, and there are other ways of solving it.

However, I think it makes sense to fail on startup if `--es.create-index-templates=false` but the template is not found. Right now the logic is simplistic, do nothing if set to false, and potentially fail at writing (but not die), or if set to true always create a template without checking if one exists already.

**Comment by kolbitsch-lastline** [comment] 2023-10-16 21:45
> I don't follow - do you mean you use some k8s trickery to execute another container? There's no "init" in the ingester.

apologies. Overlooked that the "init" command is part of the `jaeger-es-rollover` binary, not of the ingester itself. I have updated the description accordingly

> What is the root cause of that failure?

I'm still trying to figure that out myself. I believe it comes from a rogue index policy deleting our write alias, but I haven't found that yet.

But IMHO the root cause is not essential to the bug ticket - or, if you want, the feature request :-) 

Essentially I would like the ingester to die if it fails to write to the storage backend rather than ignore the problem and dump error after error into logs. By having the process die, I can have k8s alert me to the fact that a pod is in a restart loop. I completely understand if that's a non-default behavior (e.g., `--die-on-storage-error`), but I think it's a useful additional behavior in the k8s world

**Comment by yurishkuro** [comment] 2023-10-16 22:54
> `--die-on-storage-error`

I can only see this being viable if we can detect a specific type of error like "index not found". Dying on _any_ storage error is a terrible behavior - errors happen all the time. Restarting a process that reads from Kafka is pretty destructive, the consumer group needs to rebalance.

> By having the process die, I can have k8s alert me to the fact that a pod is in a restart loop.

You can also set up an alert on the db error rate in the ingester, it has metrics for that.

To summarize, I am not convinced that this would be a good feature. Building out code to handle a special case that happens not only rarely, but only in your specific installation due to potential other intervening factors, is not a good investment if it can already be handled reasonably by the default & generic mechanism (log error, bump metric).

**Comment by kolbitsch-lastline** [comment] 2023-10-17 00:04
> I can only see this being viable if we can detect a specific type of error like "index not found". Dying on any storage error is a terrible behavior - errors happen all the time. Restarting a process that reads from Kafka is pretty destructive, the consumer group needs to rebalance.

well, maybe after a retry that is not recoverable. But I don't quite see the use in just ignoring such errors.

Does the current behavior retry indefinitely or will it eventually give up and move on (and ACK the messages in Kafka)?

**Comment by yurishkuro** [comment] 2023-10-17 01:03
Yes, it will give up and continue. Sometimes poison pill messages can get into Kafka that always fail to be stored as spans - Jaeger is designed to not block everything on those, it will try a few times and move on.

**Comment by kolbitsch-lastline** [comment] 2023-10-17 17:26
>  Yes, it will give up and continue. Sometimes poison pill messages can get into Kafka that always fail to be stored as spans - Jaeger is designed to not block everything on those, it will try a few times and move on.

ok, good to know.

I hear what you are saying and am not arguing the default behavior should change, but IMHO this type of error-handling should be configurable.

In my env, I'd like to not lose data and be able to see what data the ingester is stumbling over so I can fix bad data on the source rather than ignoring it in the backend.

but if you think it's not a feature you want in Jaeger, I'll accept that answer

**Comment by yurishkuro** [comment] 2023-10-17 17:57
> In my env, I'd like to not lose data and be able to see what data the ingester is stumbling over so I can fix bad data on the source rather than ignoring it in the backend.

It's not ignoring it, it's logging an error which you can still monitor and in theory go back to Kafka and retrieve the problematic message. In theory I am not opposed to having this flag if it's framed as a way to control durability guarantees. Of course, users must realize that just because there is a durability guarantee in the collector it does not mean that they are not losing data - the path from SDKs to the backend is usually also implemented on a best-effort basis.

**Comment by jkowall** [comment] 2024-06-08 21:45
Dupe of : https://github.com/jaegertracing/jaeger/issues/4852 when I read this one....

**Comment by jkowall** [comment] 2024-06-08 21:45
Seems like a non-issue

**Closed by jkowall** 2024-06-08 21:45 UTC
Labels: bug
