### ISSUE TITLE
Can Jaeger OTEL Agent export data to Kafka?

### ISSUE THREAD

**Issue by ning2008wisc** [jaegertracing/jaeger#2252] opened 2020-05-19 00:31 UTC
## Problem - use `jaeger_kafka` (Kafka OTEL exporter) to export data directly from Jaeger OTEL Agent to kafka?

The default exporter in Jaeger OTEL Agent is `jaeger`. I tried to override the default exporter to `jaeger_kafka`(Kafka OTEL exporter). I am wondering if this is possible and here are my attempts to do this (no success yet):

(1) `--kafka.producer.topic` `kafka.producer.brokers`: Jaeger OTEL Agent does not recognize those flags (expected).

(2) use OTEL format config file:
```
spec:
  containers:
  - args:
    - --config=/config/otel-agent-config.yml
```
```
---
data:
  otel-agent-config: |
    exporters:
      jaeger_kafka:
        topic: jaeger-test
        brokers: <some_broker_url>:9092
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          exporters: [jaeger_kafka]
```
The logs from `jaeger-agent` look like:
```
2020-05-19T00:15:19.474Z	INFO	builder/exporters_builder.go:281	Exporter is enabled.	{"component_kind": "exporter", "exporter": "jaeger_kafka"}
2020-05-19T00:15:19.474Z	WARN	builder/exporters_builder.go:238	Exportee is not associated with any pipeline and will not export data.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
github.com/open-telemetry/opentelemetry-collector/service/builder.(*ExportersBuilder).buildExporter
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/builder/exporters_builder.go:238
github.com/open-telemetry/opentelemetry-collector/service/builder.(*ExportersBuilder).Build
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/builder/exporters_builder.go:174
github.com/open-telemetry/opentelemetry-collector/service.(*Application).setupPipelines
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/service.go:301
github.com/open-telemetry/opentelemetry-collector/service.(*Application).setupConfigurationComponents
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/service.go:277
github.com/open-telemetry/opentelemetry-collector/service.(*Application).execute
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/service.go:399
github.com/open-telemetry/opentelemetry-collector/service.New.func1
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/service.go:150
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.6/command.go:840
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.6/command.go:945
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.6/command.go:885
github.com/open-telemetry/opentelemetry-collector/service.(*Application).Start
	github.com/open-telemetry/opentelemetry-collector@v0.3.1-0.20200512031848-f588c89b4778/service/service.go:450
main.main
	command-line-arguments/main.go:88
runtime.main
	runtime/proc.go:203
2020-05-19T00:15:19.474Z	INFO	service/service.go:306	Starting exporters...
2020-05-19T00:15:19.474Z	INFO	builder/exporters_builder.go:89	Exporter is starting...	{"component_kind": "exporter", "component_type": "jaeger_kafka", "component_name": "jaeger_kafka"}
2020-05-19T00:15:19.474Z	INFO	builder/exporters_builder.go:94	Exporter started.	{"component_kind": "exporter", "component_type": "jaeger_kafka", "component_name": "jaeger_kafka"}
2020-05-19T00:15:19.474Z	INFO	builder/exporters_builder.go:89	Exporter is starting...	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
2020-05-19T00:15:19.474Z	INFO	builder/exporters_builder.go:94	Exporter started.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
2020-05-19T00:15:19.474Z	INFO	builder/pipelines_builder.go:188	Pipeline is enabled.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-05-19T00:15:19.474Z	INFO	service/service.go:319	Starting processors...
2020-05-19T00:15:19.474Z	INFO	builder/pipelines_builder.go:51	Pipeline is starting...	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-05-19T00:15:19.474Z	INFO	builder/pipelines_builder.go:61	Pipeline is started.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-05-19T00:15:19.474Z	INFO	builder/receivers_builder.go:223	Receiver is enabled.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger", "datatype": "traces"}
2020-05-19T00:15:19.474Z	INFO	service/service.go:331	Starting receivers...
2020-05-19T00:15:19.474Z	INFO	builder/receivers_builder.go:74	Receiver is starting...	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
2020-05-19T00:15:19.474Z	INFO	builder/receivers_builder.go:79	Receiver started.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
2020-05-19T00:15:19.474Z	INFO	healthcheck/handler.go:128	Health Check state change	{"component_kind": "extension", "status": "ready"}
2020-05-19T00:15:19.474Z	INFO	service/service.go:233	Everything is ready. Begin running and processing data.
```
It seems no error, but I launched a kafka console consumer and did not observe data produced to the topic, when applications generates some spans from upstream to Jaeger OTEL Agent.

As title, I would like to know if Jaeger OTEL Agent can export data to Kafka? If yes, how to do it correctly.

**Comment by ning2008wisc** [comment] 2020-05-19 02:32
from my experiments, it seems the applications can directly sends spans to Jaeger OTEL Collector via http thrift (`http://jaeger-collector:14268/api/traces`) and Jaeger OTEL Collector can export the spans to Kafka via `kafka.producer.*`.

Still wondering if there is a way for Jaeger OTEL Agent to export spans directly to Kafka, since the jaeger receiver of Jaeger OTEL Agent is based on `UDP` (which may have a better performance than TCP), or add `UDP` jaeger receiver to Jaeger OTEL Collector?

Thanks

**Comment by yurishkuro** [comment] 2020-05-19 04:41
jaeger-otel collector and agent are practically the same binary, but @pavolloffay would be able to answer more authoritatively.

**Comment by pavolloffay** [comment] 2020-05-19 07:23
The configuration looks correct. Maybe the OTEL collector is failing during the config validation on unused exporters. I will have a look at this.

**Comment by pavolloffay** [comment] 2020-05-25 15:53
The collector starts well, the printed stacktrace is not causing any issues. 

```
2020-05-19T00:15:19.474Z	WARN	builder/exporters_builder.go:238	Exportee is not associated with any pipeline and will not export data.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
```

I have submitted a PR to fix the logging https://github.com/open-telemetry/opentelemetry-collector/pull/1018

**Comment by ning2008wisc** [comment] 2020-05-26 05:24
@pavolloffay thanks for looking into. 

with the following otel-collector config, could we override the default exporter (e.g. jaeger) with `jaeger_kafka` exporter?

```
---
data:
  otel-agent-config: |
    exporters:
      jaeger_kafka:
        topic: jaeger-test
        brokers: <some_broker_url>:9092
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          exporters: [jaeger_kafka]
```

**Comment by pavolloffay** [comment] 2020-05-26 07:56
Yes, the user-defined pipeline always overrides the default configuration

**Comment by ning2008wisc** [comment] 2020-05-26 14:49
thanks @pavolloffay. once https://github.com/open-telemetry/opentelemetry-collector/pull/1018 is merged, I will test this configuration again and report the updates.

**Comment by pavolloffay** [comment] 2020-06-02 14:22
@ning2008wisc any updates?

**Comment by ning2008wisc** [comment] 2020-06-02 17:26
@pavolloffay from the `jaeger-OTEL-agent` log, I still see the warning about `the default exporter (jaeger) is not associated with any pipeline`. Here is the output:

```
2020-06-02T17:20:27.714Z	INFO	service/service.go:382	Starting Jaeger OpenTelemetry Agent...	{"Version": "v1.18.0", "GitHash": "312bda7a80e2020daa40229c4bffaa32c906cc1f", "NumCPU": 16}
2020-06-02T17:20:27.714Z	INFO	service/service.go:221	Setting up own telemetry...
2020-06-02T17:20:27.715Z	INFO	service/telemetry.go:94	Serving Prometheus metrics	{"address": "localhost:8888", "legacy_metrics": true, "new_metrics": false, "level": 3, "service.instance.id": ""}
2020-06-02T17:20:27.748Z	INFO	service/service.go:259	Loading configuration...
2020-06-02T17:20:27.762Z	INFO	service/service.go:270	Applying configuration...
2020-06-02T17:20:27.762Z	INFO	service/service.go:291	Starting extensions...
2020-06-02T17:20:27.762Z	INFO	builder/extensions_builder.go:53	Extension is starting...	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check"}
2020-06-02T17:20:27.762Z	INFO	healthcheckextension/healthcheckextension.go:40	Starting health_check extension	{"component_kind": "extension", "config": {"TypeVal":"health_check","NameVal":"health_check","Port":13133}}
2020-06-02T17:20:27.762Z	INFO	builder/extensions_builder.go:59	Extension started.	{"component_kind": "extension", "component_type": "health_check", "component_name": "health_check"}
2020-06-02T17:20:27.762Z	WARN	builder/exporters_builder.go:239	Exporter is not associated with any pipeline and will not export data.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
go.opentelemetry.io/collector/service/builder.(*ExportersBuilder).buildExporter
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/builder/exporters_builder.go:239
go.opentelemetry.io/collector/service/builder.(*ExportersBuilder).Build
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/builder/exporters_builder.go:175
go.opentelemetry.io/collector/service.(*Application).setupPipelines
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/service.go:301
go.opentelemetry.io/collector/service.(*Application).setupConfigurationComponents
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/service.go:277
go.opentelemetry.io/collector/service.(*Application).execute
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/service.go:399
go.opentelemetry.io/collector/service.New.func1
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/service.go:150
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v0.0.6/command.go:840
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v0.0.6/command.go:945
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v0.0.6/command.go:885
go.opentelemetry.io/collector/service.(*Application).Start
	go.opentelemetry.io/collector@v0.3.1-0.20200525211919-118e5d41fec3/service/service.go:450
main.main
	command-line-arguments/main.go:88
runtime.main
	runtime/proc.go:203
2020-06-02T17:20:27.762Z	INFO	kafka/factory.go:68	Kafka factory	{"component_kind": "exporter", "component_type": "jaeger_kafka", "component_name": "jaeger_kafka", "producer builder": {"Brokers":["<some_broker_url:9092>"],"RequiredAcks":1,"Compression":0,"CompressionLevel":0,"ProtocolVersion":"","BatchLinger":0,"BatchSize":0,"BatchMaxMessages":0,"Authentication":"none","Kerberos":{"ServiceName":"kafka","Realm":"","UseKeyTab":false,"Username":"","Password":"","ConfigPath":"/etc/krb5.conf","KeyTabPath":"/etc/security/kafka.keytab"},"TLS":{"Enabled":false,"CAPath":"","CertPath":"","KeyPath":"","ServerName":"","ClientCAPath":"","SkipHostVerify":false},"PlainText":{"UserName":"","Password":""}}, "topic": "jaeger-test"}
2020-06-02T17:20:27.976Z	INFO	builder/exporters_builder.go:306	Exporter is enabled.	{"component_kind": "exporter", "exporter": "jaeger_kafka"}
2020-06-02T17:20:27.976Z	INFO	service/service.go:306	Starting exporters...
2020-06-02T17:20:27.976Z	INFO	builder/exporters_builder.go:90	Exporter is starting...	{"component_kind": "exporter", "component_type": "jaeger_kafka", "component_name": "jaeger_kafka"}
2020-06-02T17:20:27.976Z	INFO	builder/exporters_builder.go:95	Exporter started.	{"component_kind": "exporter", "component_type": "jaeger_kafka", "component_name": "jaeger_kafka"}
2020-06-02T17:20:27.976Z	INFO	builder/exporters_builder.go:90	Exporter is starting...	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
2020-06-02T17:20:27.976Z	INFO	builder/exporters_builder.go:95	Exporter started.	{"component_kind": "exporter", "component_type": "jaeger", "component_name": "jaeger"}
2020-06-02T17:20:27.976Z	INFO	builder/pipelines_builder.go:205	Pipeline is enabled.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-06-02T17:20:27.976Z	INFO	service/service.go:319	Starting processors...
2020-06-02T17:20:27.976Z	INFO	builder/pipelines_builder.go:52	Pipeline is starting...	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-06-02T17:20:27.976Z	INFO	builder/pipelines_builder.go:62	Pipeline is started.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2020-06-02T17:20:27.976Z	INFO	builder/receivers_builder.go:234	Receiver is enabled.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger", "datatype": "traces"}
2020-06-02T17:20:27.976Z	INFO	service/service.go:331	Starting receivers...
2020-06-02T17:20:27.976Z	INFO	builder/receivers_builder.go:74	Receiver is starting...	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
2020-06-02T17:20:27.976Z	INFO	builder/receivers_builder.go:79	Receiver started.	{"component_kind": "receiver", "component_type": "jaeger", "component_name": "jaeger"}
2020-06-02T17:20:27.976Z	INFO	healthcheck/handler.go:128	Health Check state change	{"component_kind": "extension", "status": "ready"}
2020-06-02T17:20:27.976Z	INFO	service/service.go:233	Everything is ready. Begin running and processing data.```

**Comment by pavolloffay** [comment] 2020-06-02 18:13
Did you update the image?

**Comment by ning2008wisc** [comment] 2020-06-02 18:21
I am using `image: jaegertracing/jaeger-opentelemetry-agent`

Seems to me that the above image is updated 9 hours ago which should be built on the latest image of `OTEL-collector`: https://hub.docker.com/r/jaegertracing/jaeger-opentelemetry-agent

**Comment by pavolloffay** [comment] 2020-06-04 10:08
I am not able to reproduce your issue see the details below. You are probably still using the old image, I would recommend running docker rm and pull the new image. I am closing this, if the issue is still present please reopen.

Start kafka
```
docker run --rm -it  -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 --rm spotify/kafka
```

OTEL config:
```
exporters:
  jaeger_kafka:
    topic: jaeger-test
    brokers: localhost:9092
service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [jaeger_kafka]
```

Run Jager OTEL agent
```
docker run --rm -it --net=host -v ${PWD}:/config jaegertracing/jaeger-opentelemetry-agent --config=/config/conf-agent.yam
```

List Kafka topics
```
docker exec -it b66adf748782 /bin/bash                                                    12:07 
root@b66adf748782:/# echo $KAFKA_HOME
/opt/kafka_2.11-0.10.1.0
root@b66adf748782:/# $KAFKA_HOME/bin/kafka-topics.sh --list --zookeeper localhost:2181
jaeger-test
```

**Closed by pavolloffay** 2020-06-04 10:08 UTC
Labels: area/otel

**Comment by ning2008wisc** [comment] 2020-06-05 06:13
thanks @pavolloffay
