### ISSUE TITLE
how to connection kafka and jaeger ingester

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1608] opened 2019-06-17 16:01 UTC
I run  this command in my termial: docker run -p 14270:14270 -p 14271:14271 -e SPAN_STORAGE_TYPE=cassandra -e CASSANDRA_SERVERS=172.17.0.2  -e CASSANDRA_KEYSPACE=jaeger_v1_dc1 jaegertracing/jaeger-ingester 

And I got this error, It looks like there is a connection problem between jaeger and kafka

2019/06/17 15:57:09 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1560787029.852812,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1560787029.852992,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1560787029.8530416,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14270}
{"level":"info","ts":1560787029.85307,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14270,"health-status":"unavailable"}
{"level":"info","ts":1560787029.873604,"caller":"cassandra/factory.go:92","msg":"Cassandra archive storage configuration is empty, skipping"}
{"level":"fatal","ts":1560787030.6309447,"caller":"ingester/main.go:74","msg":"Unable to create consumer","error":"kafka: client has run out of available brokers to talk to (Is your cluster reachable?)","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:74\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:105\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}

**Comment by yurishkuro** [comment] 2019-06-17 16:12
you have not specified any parameters pointing to your Kafka brokers

**Comment by zheyiyi** [comment] 2019-06-17 19:27
# see kafka.server.KafkaConfig for additional details and defaults

############################# Server Basics #############################

# The id of the broker. This must be set to a unique integer for each broker.
broker.id=0

############################# Socket Server Settings #############################

# The address the socket server listens on. It will get the value returned from 
# java.net.InetAddress.getCanonicalHostName() if not configured.
#   FORMAT:
#     listeners = listener_name://host_name:port
#   EXAMPLE:
#     listeners = PLAINTEXT://your.host.name:9092
listeners = PLAINTEXT://127.0.0.1:9092


我的kafka broker就是127.0.0.1:9092， 因为jager 默认的就是这个   --kafka.consumer.brokers string                   The comma-separated list of kafka brokers. i.e. '127.0.0.1:9092,0.0.0:1234' (default "127.0.0.1:9092")
所以我没配置

**Comment by yurishkuro** [comment] 2019-06-23 17:28
duplicate of #1619

**Closed by yurishkuro** 2019-06-23 17:28 UTC
Labels: question
