### ISSUE TITLE
CONTRIBUTING.md not updated according to location of static assets

### ISSUE THREAD

**Issue by rneha725** [jaegertracing/jaeger#1841] opened 2019-10-07 08:12 UTC
## Requirement - what kind of business use case are you trying to solve?

Installation steps of jaeger-ui, while running inside jaeger.
## Problem - what in Jaeger blocks you from solving the requirement?

Command mentioned in CONTRIBUTING.md is not updated.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

In [CONTRIBUTING.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md#running-local-build-with-the-ui), the command should be `go run ./cmd/all-in-one/main.go --query.static-files jaeger-ui/packages/jaeger-ui/build`

**Comment by yurishkuro** [comment] 2019-10-08 06:35
I do not believe it is necessary. `make build-ui` command packages UI assets into Go binary directly

**Comment by rneha725** [comment] 2019-10-08 16:16
Sorry, issue was in my go installation. I did not set the path for `$GOPATH/bin`. Also, this step is not mentioned in steps, should I add?

**Comment by rneha725** [comment] 2019-10-08 16:35
I have some changes for the above and opened a pull request for the corresponding [issue](https://github.com/jaegertracing/jaeger/issues/1834)

**Comment by yurishkuro** [comment] 2019-11-02 20:02
@meha725 I am not seeing a pull request, only some commits referencing the issue.

The step of adding `$GOPATH/bin` to PATH is part of standard Go toolchain installation. But I have no objections mentioning it in the instructions.

I am going to close this as it's mostly a duplicate of #1834. If you find omissions in the instructions, I recommend (a) making a note in a comment to #1834, and (b) opening a pull request to fix it.

**Closed by yurishkuro** 2019-11-02 20:02 UTC
Labels: documentation, good first issue, hacktoberfest
