### ISSUE TITLE
Failed to create index/resource already exists creating spans when using ElasticSearch

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger#665] opened 2018-01-25 14:33 UTC
While running a simple performance test and using ElasticSearch as storage I a number of "failed to create index" errors on the collector

I did the following:
-- Download elasticsearch 6.1.2 from https://www.elastic.co/downloads/elasticsearch and ran ./bin/elasticsearch
-- Ran the collector with: SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/collector/main.go --collector.queue-size=3000000 --es.bulk.size=10000000 --es.bulk.workers=10 --es.bulk.flush-interval=1s 
-- git clone git@github.com:Hawkular-QE/jaeger-standalone-performance-tests.git
-- DELAY=10 THREAD_COUNT=10 ELASTICSEARCH_HOST=localhost SPAN_STORAGE_TYPE=elasticsearch USE_AGENT_OR_COLLECTOR=collector DURATION_IN_MINUTES=1 mvn clean -Dtest=SimpleTest#createTracesTest test

In one particular case the test failed as it created 59040 spans but only found 58943 in elasticsearch.  For each of the missing spans the collector produced a pair of the following error messages.

`{"level":"error","ts":1516890288.1260505,"caller":"spanstore/writer.go:190","msg":"Failed to create index","trace_id":"b36e3fa8b97bb7c6","span_id":"b36e3fa8b97bb7c6","error":"elastic: Error 400 (Bad Request): index [jaeger-span-2018-01-25/xcVS2i4VQh6fZ8LsytrXgw] already exists [type=resource_already_exists_exception]","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:190\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:152\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:123\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
{"level":"error","ts":1516890288.1261024,"caller":"app/span_processor.go:103","msg":"Failed to save span","error":"Failed to create index: elastic: Error 400 (Bad Request): index [jaeger-span-2018-01-25/xcVS2i4VQh6fZ8LsytrXgw] already exists [type=resource_already_exists_exception]","errorVerbose":"elastic: Error 400 (Bad Request): index [jaeger-span-2018-01-25/xcVS2i4VQh6fZ8LsytrXgw] already exists [type=resource_already_exists_exception]\nFailed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:191\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:152\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:123\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:103\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/kearls/go/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}`

**Comment by pavolloffay** [comment] 2018-01-25 16:35
Hi @kevinearls thanks for reporting. Nit could you please format log output and commands like `this`.

**Comment by pavolloffay** [comment] 2018-01-25 16:55
It seems that this is only related to elasticsearch `6.x`. I was able to reproduce the error. 

This error does not occur when using `5.x` (I am using `5.6.6`). 

We are using golang elastic client `5.x` which is compatible with ES5 https://github.com/olivere/elastic#releases

Our docs says that we are compatible with ES 5 and 6 http://jaeger.readthedocs.io/en/latest/deployment/#elasticsearch. I think we should change this. cc @yurishkuro

**Comment by kevinearls** [comment] 2018-01-26 09:37
I'm not able to reproduce this with 5.6.6 either, even after running for 30 minutes, so I'm going to close this.

**Comment by jpkrohling** [comment] 2018-07-06 08:24
I'm reopening, as we got another report for this problem under ES 6.x. Either we should change the docs to mention that we do not support 6.x, or we should fix the underlying issue :-)

**Comment by jpkrohling** [comment] 2018-07-06 08:30
Perhaps it's then a good idea to not remove, but say that "there are issues reported against 6.x" and link to here?

**Comment by pavolloffay** [comment] 2018-07-06 08:35
I would not encourage users to use 6.x if our components do not fully support it. 

The version of ES client we are pulling is compatible with ES 5.x https://github.com/olivere/elastic#releases

**Comment by pavolloffay** [comment] 2018-07-06 08:36
For ES 6 support there is a separate issue https://github.com/jaegertracing/jaeger/issues/637

**Comment by misojiwon3** [comment] 2018-07-06 08:42
I got same issue with @kevinearls on my jaeger-collector. 

Errors like below.

{"level":"info","ts":1530861463.72645,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1530861463.7328868,"caller":"static/strategy_store.go:77","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1530861463.7332094,"caller":"collector/main.go:141","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1530861463.7334013,"caller":"collector/main.go:149","msg":"Starting Jaeger Collector HTTP server","http-port":14268}
{"level":"info","ts":1530861463.7334604,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"error","ts":1530861490.2414696,"caller":"spanstore/writer.go:187","msg":"Failed to create index","trace_id":"72753077633cc236","span_id":"37d42b0700280967","error":"elastic: Error 400 (Bad Request): index [jaeger-service-2018-07-06/Z5j32laiSg-ptFcPIo_Ttg] already exists [type=resource_already_exists_exception]","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:187\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:149\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:116\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
{"level":"error","ts":1530861490.241552,"caller":"app/span_processor.go:102","msg":"Failed to save span","error":"Failed to create index: elastic: Error 400 (Bad Request): index [jaeger-service-2018-07-06/Z5j32laiSg-ptFcPIo_Ttg] already exists [type=resource_already_exists_exception]","errorVerbose":"elastic: Error 400 (Bad Request): index [jaeger-service-2018-07-06/Z5j32laiSg-ptFcPIo_Ttg] already exists [type=resource_already_exists_exception]\nFailed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:188\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:149\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:116\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}


Some spans are stored and some other are not. Is is caused partially.

My ES version is 6.1.1 and clustered with three nodes.


If you need additional information about this issue, please comment.

**Comment by pavolloffay** [comment] 2018-07-06 08:48
@misojiwon3 thanks for the report! The ES 6.x is not fully supported at the moment. For more info please see https://github.com/jaegertracing/jaeger/issues/637.

**Comment by yurishkuro** [comment] 2018-07-06 17:58
@pavolloffay not sure I follow this - how is "index already exists" issue specific to ES 6.x?  Is this a race condition among the collectors?

**Comment by pavolloffay** [comment] 2018-07-09 07:37
@yurishkuro this happens only with ES 6.x. Maybe it could be somehow fixed on our side but it seems that ES client version we are pulling is tested and guaranteed to work with es 5.x

**Comment by pavolloffay** [comment] 2018-07-09 08:44
The issue is that ES 6.x changed REST API. Fix is in https://github.com/jaegertracing/jaeger/pull/921. 

The problem would not have been resolved even if we updated ES client to 6.x version as we compare strings in our impl.

**Closed** 2018-07-09 14:22 UTC
Labels: bug, review, storage
