### ISSUE TITLE
Not able to have quality metrics for hotrod application 

### ISSUE THREAD

**Issue by vvvprabhakar** [jaegertracing/jaeger#2313] opened 2020-06-26 11:54 UTC
Using jaeger hotrod application 
Able to see the traces
But not the quality metrics 
<img width="1440" alt="Screenshot 2020-06-26 at 5 21 09 PM" src="https://user-images.githubusercontent.com/20414336/85854271-b753ed00-b7d1-11ea-96c2-ccc9a07b03f3.png">

**Comment by jpkrohling** [comment] 2020-09-10 09:47
What is this `qualitymetrics-v2` endpoint? @yurishkuro would you know about it?

**Comment by yurishkuro** [comment] 2020-09-10 19:50
There is no open source version of qualitymetrics-v2 endpoint afaik, but it's something that's used by the UI. It's unreleased functionality at this point.

**Comment by jpkrohling** [comment] 2020-09-11 07:57
I'm confused: where is this coming from? I don't see any references for `qualitymetrics` anywhere in the Jaeger source code. Do I understand it right that the HotROD has a link to this endpoint?

**Comment by yurishkuro** [comment] 2020-09-11 16:17
There is a code in the UI that calls this endpoint, but there is no server-side implementation.

**Comment by jpkrohling** [comment] 2020-09-14 08:15
> There is a code in the UI that calls this endpoint

Sorry for asking again, but *where*? If it's under Hot ROD or Jaeger UI, we need to remove this...

**Comment by yurishkuro** [comment] 2020-09-14 22:18
https://github.com/jaegertracing/jaeger-ui/blob/92a840680a10a6b07275d983b5179fa47d7628ae/packages/jaeger-ui/src/api/jaeger.js#L93

**Comment by jpkrohling** [comment] 2020-09-15 07:59
My grep skills failed on me this time. Looks like a good first issue.

**Comment by yurishkuro** [comment] 2020-09-15 15:39
Sorry, but what is the issue specifically? Implementing the whole end-to-end trace quality metrics pipeline is probably not a "good first issue".

**Comment by jpkrohling** [comment] 2020-09-16 08:01
To me, the issue is that we have a link in the UI to a service that doesn't exist, so, it should be removed. I guess it's an issue for the jaeger-ui repo instead then. If you agree, I'll move it there, but if you think it is not an actual problem, we can just close it.

**Comment by yurishkuro** [comment] 2020-09-16 16:14
We don't show the link by default, afaik. Here's all-in-one:

![image](https://user-images.githubusercontent.com/3523016/93364002-067c4d80-f816-11ea-8527-b55c712fa850.png)

The link needs to be explicitly available via UI configuration. I think it's fine to leave that as is, and we should just finish the trace quality metrics pipeline and add that as a service.

**Comment by oalbacha** [comment] 2020-10-07 21:18
Hi,
Is this issue still open? I would like to contribute if it is.

**Comment by yurishkuro** [comment] 2020-10-08 00:11
Hi, sorry, I am closing this as invalid.

**Comment by yurishkuro** [comment] 2020-10-08 00:12
Please check other "good first issue" issues.

**Closed by yurishkuro** 2020-10-08 00:11 UTC
Labels: invalid
