### ISSUE TITLE
Jaeger-collector Unable to write to cassandra

### ISSUE THREAD

**Issue by maniaabdi** [jaegertracing/jaeger#988] opened 2018-08-14 01:51 UTC
hello again every one
it seems that I was able to deploy jaeger
however I keep getting this error
``` {"level":"error","ts":1534210873.243136,"caller":"app/span_processor.go:102","msg":"Failed to save span","error":"Failed to insert span: failed to Exec query '[query statement=\"\\n\\t\\tINSERT\\n\\t\\tINTO traces(trace_id, span_id, span_hash, parent_id, operation_name, flags,\\n\\t\\t\\t\\t start_time, duration, tags, logs, refs, process)\\n\\t\\tVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\" values=[1c8dabda51c4cf3a 4813662001497872486 191740414626613060 0 op 1 1534210872426849 572 [] [] [{RefType:child-of TraceID:1c8dabda51c4cf3a SpanID:2057489558941257530}] {ServiceName:client.rgw Tags:[{Key:jaeger.version ValueType:string ValueString:C++-0.5.0 ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]} {Key:hostname ValueType:string ValueString:mania-exp ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]} {Key:ip ValueType:string ValueString:127.0.0.1 ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]}]}] consistency=LOCAL_ONE]': unconfigured table traces","errorVerbose":"unconfigured table traces\nfailed to Exec query '[query statement=\"\\n\\t\\tINSERT\\n\\t\\tINTO traces(trace_id, span_id, span_hash, parent_id, operation_name, flags,\\n\\t\\t\\t\\t start_time, duration, tags, logs, refs, process)\\n\\t\\tVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\" values=[1c8dabda51c4cf3a 4813662001497872486 191740414626613060 0 op 1 1534210872426849 572 [] [] [{RefType:child-of TraceID:1c8dabda51c4cf3a SpanID:2057489558941257530}] {ServiceName:client.rgw Tags:[{Key:jaeger.version ValueType:string ValueString:C++-0.5.0 ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]} {Key:hostname ValueType:string ValueString:mania-exp ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]} {Key:ip ValueType:string ValueString:127.0.0.1 ValueBool:false ValueInt64:0 ValueFloat64:0 ValueBinary:[]}]}] consistency=LOCAL_ONE]'\ngithub.com/jaegertracing/jaeger/pkg/cassandra/metrics.(*Table).Exec\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/cassandra/metrics/table.go:50\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*SpanWriter).writeSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/writer.go:167\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*SpanWriter).WriteSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/writer.go:139\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361\nFailed to insert span\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*SpanWriter).logError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/writer.go:273\ngithub.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore.(*SpanWriter).writeSpan\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/cassandra/spanstore/writer.go:168\ngithub.com/jaegertracing/jaeger/plug ```
It seems that I am unable to save any span
Any help is appreciated
and I cannot visualize my span on jaeger-ui :(

maniaabdi @maniaabdi 21:47
based on log msg it seems the collector is able to get span from agent however it cannot be saved
I use cassandra as backend storage

**Comment by isaachier** [comment] 2018-08-14 01:55
Note the error message : `unconfigured table traces`. You need to set up the database using the scripts provided in the scripts directory before you start using the collector. Please look at the docs online for more details.

**Comment by maniaabdi** [comment] 2018-08-14 02:04
Thanks alot. I really appreciate your help when I run that script I get 

``` <stdin>:54:ConfigurationException: <Error from server: code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'"> ``` and I run the script as 

``` MODE=test bash ./plugin/storage/cassandra/schema/create.sh | cqlsh ```
and also in order to be able to run cqlsh I needed to set the 

``` #JAEGER COLLECTOR START
export CQLSH_NO_BUNDLED=TRUE
``` 
in .bashrc

**Comment by isaachier** [comment] 2018-08-14 02:28
I believe this is a Cassandra issue. See what version you are running. IIRC Jaeger expects Cassandra 3. The error message there should help you find the issue.

**Comment by maniaabdi** [comment] 2018-08-14 03:07
Thanks alot for your help. I reinstall Cassandra using version 3.11 and everything works fine. Thanks

**Comment by jpkrohling** [comment] 2018-08-14 10:06
I'm closing this issue, as it seems it's not a bug.

**Closed by jpkrohling** 2018-08-14 10:06 UTC

**Comment by kingeasternsun** [comment] 2018-12-27 04:54
@maniaabdi  I meet the same issue, how u uninstall the Cassandra and reinstall the 3.11

**Comment by kingeasternsun** [comment] 2018-12-27 04:56
myCassandra
```
[cqlsh 5.0.1 | Cassandra 3.6 | CQL spec 3.4.2 | Native protocol v4]

````

when i execute

```MODE=test ./create.sh | cqlsh
Using template file ./v001.cql.tmpl with parameters:
    mode = test
    datacenter = test
    keyspace = jaeger_v1_test
    replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
    trace_ttl = 172800
    dependencies_ttl = 0
<stdin>:54:ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'">
<stdin>:100:ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'">
<stdin>:117:ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'">
<stdin>:136:ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'">
<stdin>:156:ConfigurationException: <ErrorMessage code=2300 [Query invalid because of configuration issue] message="Unable to find compaction strategy class 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'">

```

**Comment by yurishkuro** [comment] 2018-12-27 08:03
It appears TimeWindowCompactionStrategy was introduced in a later version: https://issues.apache.org/jira/browse/CASSANDRA-9666
