### ISSUE TITLE
panic: proto: duplicate extension registered: descriptor.MethodOptions 72295728

### ISSUE THREAD

**Issue by lucasponce** [jaegertracing/jaeger#3276] opened 2021-09-20 16:03 UTC
Jaegertracing and Istio.io dependencies have some problem to work together.

https://github.com/istio/istio/issues/35277

I couldn't find a good workaround to avoid this problem, that can be easily reproduce with this example:

https://github.com/lucasponce/lucas-demos/blob/main/go.mod

So, I'm opening both issues in jaegertracing and istio projects as I think that consumer of both clients, like the Kiali project, are affected by this.

What would be the ideal ? To have a jaeger client that can be consumed by go programs to have minimal dependencies to use the api_v2 and query.proto APIs.

Something like this minor PoC:

https://github.com/lucasponce/jaeger-backend-client

But ensuring that it has not incompability with other clients (kubernetes, istio) that are also using grpc clients.

**Comment by yurishkuro** [comment] 2021-09-20 16:43
Sorry, I don't follow what the problem is and what you're trying to do. If you need to access Jaeger data via gRPC/proto, then we publish the proto files in jaeger-idl and you can do whatever you want with them, it does not create any dependency on jaeger/go.mod.

**Comment by lucasponce** [comment] 2021-09-20 16:54
@yurishkuro the api_v2 has dependencies with the jaegertracing/jaeger/model package, so you can't recreate them without cloning the main jaeger project.

https://github.com/kiali/kiali/blob/master/jaeger/client.go#L15

Perhaps if there is a way to perform that queries without those dependencies using grpc (api_v2, I saw changes in api_v3) I'm willing to refactor the Kiali codebase.

**Comment by yurishkuro** [comment] 2021-09-20 17:12
> the api_v2 has dependencies with the jaegertracing/jaeger/model package

Only if you're importing internal packages of Jaeger backend. We do not mark them `internal/` explicitly, but that is the intention. By importing them you will always run the risk of incompatibilities. Why can't you depend purely on the proto-generated classes (which you should generate yourself)? Proto is the API, not the internal `model/` package.

**Comment by lucasponce** [comment] 2021-09-20 17:17
> Proto is the API, not the internal model/ package.

I think that for the api_v2, the TraceID are still pulling the model package, also to manipulate them:

https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/query.proto#L54
https://github.com/jaegertracing/jaeger-idl/blob/master/proto/api_v2/model.proto

Kiali only performs a fetch all traces, fetch trace with ID using grpc:

https://github.com/kiali/kiali/blob/master/jaeger/client.go#L167

But for those grpc queries in api_v2, I don't see how we can bypass the model/ package.

Trying to clone the minimal dependencies and only rely with the .proto creates some kind of binary conflicts as well.

**Comment by lucasponce** [comment] 2021-09-21 15:12
@yurishkuro is there any example of similar queries that can be run against Jaeger without the need to pull the model dependency ?

If I'm failing in some aspect of the API I'd like to simplify that logic.

**Comment by yurishkuro** [comment] 2021-09-21 15:18
Well, think about how you would query Jaeger if your system was all in Java. You would not have any code dependency on Jaeger backend, you would only depend on the proto API, and would generate your own classes / gRPC client. So my suggestion is that even if your system happened to be in Go, you don't build dependencies on Jaeger code, only on the proto API.

**Comment by lucasponce** [comment] 2021-09-22 10:43
@yurishkuro I see your point, and that's should be the goal, to only depend of an auto-generated .proto.
But I think the jaeger api_v2 is not yet there, it has some dependencies with the TraceID model and the way those ids are marshalled into grpc.

Not a blocker, with some adjustments in the .proto a user may have a working example with no dependencies with the jaeger code.

https://github.com/lucasponce/jaeger-proto-client

I'd ask to see if the api_v2 could also be improved in that way, but in any case, with the workaround of the example I guess I can perform those changes in kiali code base, we'll remove the jaeger dependencies and rely mostly on the .proto (with the exception to some manipulation with the custom Ids).

**Comment by yurishkuro** [comment] 2021-09-22 14:26
What trace-id dependencies are you referring to? Our internal domain model uses a custom type for ids but it does not affect how they are represented in proto - array of bytes. You may need to remove gogo annotations from proto.

**Comment by lucasponce** [comment] 2021-09-22 14:44
> What trace-id dependencies are you referring to? Our internal domain model uses a custom type for ids but it does not affect how they are represented in proto - array of bytes. You may need to remove gogo annotations from proto.

That's what I did in the example, but if you look the code, some dependency on the model is necessary:
https://github.com/lucasponce/jaeger-proto-client/blob/main/jaeger-client.go#L35

In short, the proto is not enough to access to the API, and the client needs to recreate - at least - the helpers to manipulate the ids.

**Comment by yurishkuro** [comment] 2021-09-22 15:09
Do you mean this call to `model.TraceIDFromString`?
```
	sTraceId := "2400171a1ac3b1cffde1fd36fd401ad0"
	traceId, err := model.TraceIDFromString(sTraceId)
```
I wouldn't consider it as a necessary dependency - all this function is doing is converting hex string to bytes.

**Comment by lucasponce** [comment] 2021-09-22 15:20
> but if really desired, I wouldn't mind having this conversion in jaeger-lib

Thanks, I'm still working on it. When I have tested the scenario I can add a list of potential helper that would be nice to have them in jaeger-lib.

**Comment by jkowall** [comment] 2024-06-07 20:40
Please feel free to contribute @lucasponce if it makes sense, closing this off for now due to age.

**Closed by jkowall** 2024-06-07 20:40 UTC
Labels: bug
