### ISSUE TITLE
ui: wrong units in TraceResultsScatterPlot

### ISSUE THREAD

**Issue by mirza-s** [jaegertracing/jaeger#1168] opened 2018-11-11 14:21 UTC
Units in scatter plot are not consistent with displayed data.
Units are in seconds while data points are in ms.

Docker image version: jaegertracing/all-in-one:1.7 

[![units.png](https://i.postimg.cc/gkd17zN2/units.png)](https://postimg.cc/CdPvBV33)

**Comment by istrel** [comment] 2018-11-13 14:04
I face this issue too.

I noticed that the time axis also has incorrect values. For example, in my case, I see the page in 16:51 (i.e. 4:51 pm)

`jaegertracing/all-in-one:1.8` started after 16:44. All spans are generated between 16:44 and 16:45. But according to the chart they were generated between 7 am and 9 am

<img width="1252" alt="screenshot 2018-11-13 at 16 50 41" src="https://user-images.githubusercontent.com/5306643/48417771-a6717780-e764-11e8-9f73-6a2415df8b64.png">

**Comment by istrel** [comment] 2018-11-13 14:06
@mirza-s Please, check out 1.8. 

Seems, like the issue is not reproduced on this version

**Comment by mirza-s** [comment] 2018-11-13 16:13
Issue not present in v1.8.

Thank you.

**Comment by mirza-s** [comment] 2018-11-13 16:20
While the vertical issue is resolved. It appears that the horizontal time axis is all over the place.

**Comment by ledor473** [comment] 2018-11-16 21:03
I'm seeing the same issue regarding the horizontal axis (confirmed against 1.7 and 1.8):

<img width="1555" alt="screen shot 2018-11-16 at 1 46 05 pm" src="https://user-images.githubusercontent.com/1359779/48640930-33574380-e9a6-11e8-906a-86b748cc07b9.png">

**Comment by yurishkuro** [comment] 2018-11-16 21:19
duplicate of https://github.com/jaegertracing/jaeger-ui/issues/270

**Comment by yurishkuro** [comment] 2018-11-18 04:54
should be fixed by https://github.com/jaegertracing/jaeger-ui/pull/274

**Closed by yurishkuro** 2018-11-18 04:54 UTC
