### ISSUE TITLE
Docs Website Nav Sidebars are unusable (partially)

### ISSUE THREAD

**Issue by ghostsquad** [jaegertracing/jaeger#2303] opened 2020-06-22 22:48 UTC
When viewing a page such as this:
https://www.jaegertracing.io/docs/1.18/operator/

The right side navigation bar does not scroll the content, and is usually too large to be totally visible within the window.

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/903488/85342451-8442ee00-b49f-11ea-899e-4d4a312e7c99.png">

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/903488/85342472-8c029280-b49f-11ea-954f-79fa2c9e5085.png">

Notice in these screenshots how the content has scrolled, but the navigation bar has not.

Also, when at the bottom of the page, whatever remains of the navigation bar is even more obscured.

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/903488/85342522-b6ece680-b49f-11ea-810c-75d8b70b796a.png">

**Comment by yurishkuro** [comment] 2020-06-22 23:11
Duplicate of https://github.com/jaegertracing/documentation/issues/360

**Closed by yurishkuro** 2020-06-22 23:11 UTC
Labels: bug, needs-triage
