### ISSUE TITLE
Flaky test pkg/discovery/grpcresolver/TestGRPCResolverRoundRobin (grpc_resolver_test.go)

### ISSUE THREAD

**Issue by albertteoh** [jaegertracing/jaeger#2674] opened 2020-12-01 05:07 UTC
**Describe the bug**
https://github.com/jaegertracing/jaeger/runs/1478025515?check_suite_focus=true

```
=== RUN   TestGRPCResolverRoundRobin/minPeers=7
    grpc_resolver_test.go:99: 
        	Error Trace:	grpc_resolver_test.go:99
        	            				grpc_resolver_test.go:155
        	Error:      	Should be true
        	Test:       	TestGRPCResolverRoundRobin/minPeers=7
        	Messages:   	Connection was still not up
--- FAIL: TestGRPCResolverRoundRobin (0.12s)
    --- PASS: TestGRPCResolverRoundRobin/minPeers=3 (0.02s)
    --- PASS: TestGRPCResolverRoundRobin/minPeers=5 (0.04s)
    --- FAIL: TestGRPCResolverRoundRobin/minPeers=7 (0.06s)
```

**Comment by yurishkuro** [comment] 2020-12-01 05:29
hmm, it waits for 10sec total, so doubtful that it's just the scheduling hiccup

**Comment by yurishkuro** [comment] 2021-01-11 18:12
Duplicate of #2085

**Closed by yurishkuro** 2021-01-11 18:12 UTC
Labels: bug, good first issue, help wanted
