### ISSUE TITLE
[Bug]: The duration field type of OpenSearch & Elasticsearch init template mapping is different with code implementation

### ISSUE THREAD

**Issue by gfes980615** [jaegertracing/jaeger#4801] opened 2023-10-05 07:35 UTC
### What happened?

I found the [es mappings indice template](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/mappings/fixtures/jaeger-span-7.json#L62) will create the indices with the duration field being the `long` type. 
[`long` type in ES and OpenSearch](https://opensearch.org/docs/2.1/opensearch/supported-field-types/numeric/) the range value will be `-9223372036854775808 ~ 9223372036854775807`. 
But the `writeSpan` [function uses the type in Golang](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/spanstore/dbmodel/model.go#L61) is uint64 type which value range is `0 ~ 18446744073709551615.`

When I send the duration value over the `9223372036854775807` the es will reject the span and keep retry let the data pipeline delay.
The type not mapping seems the root cause of ES rejection of the data.

---
The resulting weird duration value also makes me curious. And I tried to find out why the duration will be a value like `18446744073651552625`
I found the [function in es writer](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/spanstore/dbmodel/from_domain.go#L55) will transfer the duration type from int64 to uint64
```go
func DurationAsMicroseconds(d time.Duration) uint64 {
	return uint64(d.Nanoseconds() / 1000)
}
```

I tried to make this function calculate the weird value like below:
```go
package main

import "fmt"

func main() {
	m1 := -1 << 10
	m2 := m1 / 1000
	m3 := uint64(int64(m1) / 1000)

	fmt.Println("m1", m1)
	fmt.Println("m2", m2)
	fmt.Println("m3", m3)
}
// ------------------------
// result:
// m1 -1024
// m2 -1
// m3 18446744073709551615
``` 
According to the above test, seems this transform function will use binary conversion to make a negative number be positive number. 

How to make the `duration` value be a negative number?
I think this is a weird scenario. When I make the span's start time be the future time like below:
```go
_, e2eSpan := otel.Tracer(traceData.Subtype).Start(context.Background(), traceData.Subtype,
		// set customize start timestamp timestamp of the span
		trace.WithTimestamp(time.Now().Add(time.Minute*1))

e2eSpan.End(trace.WithTimestamp(time.Now()))
```
As a service that needs to receive all the user data, we can't control user data content. So we need to protect our backend service.

I supposed that fixing the ES type and code implementation of not corresponding issue could resolve my issue.
Or have any solution for this problem?

### Steps to reproduce

1. Customize the span start timestamp to the future timestamp
2. The jaeger backend storage use ES or OpenSearch

### Expected behavior

The data across the Jaeger can be written to ES or OpenSearch successfully

### Jaeger backend version

v1.49.0

### SDK

"go.opentelemetry.io/otel"
"go.opentelemetry.io/otel/attribute"
"go.opentelemetry.io/otel/trace"

### Pipeline

otel sdk -> otel collector -> jaeger collector -> kafka -> jaeger ingester -> AWS Opensearch

### Stogage backend

AWS OpenSearch

### Operating system

Linux

### Deployment model

Kubernetes

**Comment by yurishkuro** [comment] 2023-10-05 17:43
I don't think tweaking storage to represent malformed data is the right approach, because it duplicates the problem that now needs to be solved by every storage implementation. Instead it's best to fix the data during ingestion, whenever possible. This specific use case of `endTimestamp <= startTimestamp` is something that is easy to fix at ingestion centrally, before the data reaches the storage. We can capture the original values as extra tags, and then adjust them with some default behavior so that they satisfy the expected invariant. Typically we do this in `model/adjuster` module.

**Comment by yurishkuro** [comment] 2023-10-06 04:13
There was no unsigned long in v5 https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-types.html

**Comment by gfes980615** [comment] 2023-10-06 06:17
Yes, I mean that shouldn't the duration of the Span struct in [code](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/spanstore/dbmodel/model.go#L61) be the type of int64?

**Comment by yurishkuro** [comment] 2023-10-06 13:41
No because duration cannot be negative

**Comment by jkowall** [comment] 2024-06-08 22:10
Seems like this is not a bug.... Closing.

**Closed by jkowall** 2024-06-08 22:10 UTC
Labels: bug
