### ISSUE TITLE
Confusing `help` options for storage

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#734] opened 2018-03-09 12:33 UTC
When running the `help` command, the storage options are shown only for the "active" storage, which is either `cassandra` (the default), `memory` or `elasticsearch`. While it kinda makes sense to hide the `cassandra` options if `SPAN_STORAGE_TYPE=elasticsearch` is set, it's really confusing to omit the env var and see only the Cassandra options.

Examples:

```
$ go run ./cmd/query/main.go help
Jaeger query service provides a Web UI and an API for accessing trace data.

Usage:
  jaeger-query [flags]
  jaeger-query [command]

Available Commands:
  env         Help about environment variables
  help        Help about any command
  version     Print the version

Flags:
      --cassandra-archive.connections-per-host int           The number of Cassandra connections from a single backend instance
      --cassandra-archive.consistency string                 The Cassandra consistency level, e.g. ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE (default LOCAL_ONE)
      --cassandra-archive.enabled                            Enable extra storage
      --cassandra-archive.keyspace string                    The Cassandra keyspace for Jaeger data
      --cassandra-archive.max-retry-attempts int             The number of attempts when reading from Cassandra
      --cassandra-archive.password string                    Password for password authentication for Cassandra
      --cassandra-archive.port int                           The port for cassandra
      --cassandra-archive.proto-version int                  The Cassandra protocol version
      --cassandra-archive.servers string                     The comma-separated list of Cassandra servers
      --cassandra-archive.socket-keep-alive duration         Cassandra's keepalive period to use, enabled if > 0 (default 0s)
      --cassandra-archive.timeout duration                   Timeout used for queries (default 0s)
      --cassandra-archive.tls                                Enable TLS
      --cassandra-archive.tls.ca string                      Path to TLS CA file
      --cassandra-archive.tls.cert string                    Path to TLS certificate file
      --cassandra-archive.tls.key string                     Path to TLS key file
      --cassandra-archive.tls.server-name string             Override the TLS server name
      --cassandra-archive.tls.verify-host                    Enable (or disable) host key verification
      --cassandra-archive.username string                    Username for password authentication for Cassandra
      --cassandra.connections-per-host int                   The number of Cassandra connections from a single backend instance (default 2)
      --cassandra.consistency string                         The Cassandra consistency level, e.g. ANY, ONE, TWO, THREE, QUORUM, ALL, LOCAL_QUORUM, EACH_QUORUM, LOCAL_ONE (default LOCAL_ONE)
      --cassandra.dependency-store-data-frequency duration   Frequency of service dependency calculations (default 24h0m0s)
      --cassandra.keyspace string                            The Cassandra keyspace for Jaeger data (default "jaeger_v1_test")
      --cassandra.max-retry-attempts int                     The number of attempts when reading from Cassandra (default 3)
      --cassandra.password string                            Password for password authentication for Cassandra
      --cassandra.port int                                   The port for cassandra
      --cassandra.proto-version int                          The Cassandra protocol version (default 4)
      --cassandra.servers string                             The comma-separated list of Cassandra servers (default "127.0.0.1")
      --cassandra.socket-keep-alive duration                 Cassandra's keepalive period to use, enabled if > 0 (default 0s)
      --cassandra.span-store-write-cache-ttl duration        The duration to wait before rewriting an existing service or operation name (default 12h0m0s)
      --cassandra.timeout duration                           Timeout used for queries (default 0s)
      --cassandra.tls                                        Enable TLS
      --cassandra.tls.ca string                              Path to TLS CA file
      --cassandra.tls.cert string                            Path to TLS certificate file
      --cassandra.tls.key string                             Path to TLS key file
      --cassandra.tls.server-name string                     Override the TLS server name
      --cassandra.tls.verify-host                            Enable (or disable) host key verification (default true)
      --cassandra.username string                            Username for password authentication for Cassandra
      --config-file string                                   Configuration file in JSON, TOML, YAML, HCL, or Java properties formats (default none). See spf13/viper for precedence.
  -h, --help                                                 help for jaeger-query
      --log-level string                                     Minimal allowed log Level. For more levels see https://github.com/uber-go/zap (default "info")
      --metrics-backend string                               Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
      --metrics-http-route string                            Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
      --query.health-check-http-port int                     The http port for the health check service (default 16687)
      --query.port int                                       The port for the query service (default 16686)
      --query.prefix string                                  The prefix for the url of the query service (default "api")
      --query.static-files string                            The path for the static assets for the UI (default "jaeger-ui-build/build/")
      --query.ui-config string                               The path to the UI configuration file in JSON format
      --span-storage.type string                             Deprecated; please use SPAN_STORAGE_TYPE environment variable

Use "jaeger-query [command] --help" for more information about a command.
```

With `elasticsearch` as the storage:

```
$ SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/query/main.go help
Jaeger query service provides a Web UI and an API for accessing trace data.

Usage:
  jaeger-query [flags]
  jaeger-query [command]

Available Commands:
  env         Help about environment variables
  help        Help about any command
  version     Print the version

Flags:
      --config-file string                 Configuration file in JSON, TOML, YAML, HCL, or Java properties formats (default none). See spf13/viper for precedence.
      --es.bulk.actions int                The number of requests that can be enqueued before the bulk processor decides to commit (default 1000)
      --es.bulk.flush-interval duration    A time.Duration after which bulk requests are committed, regardless of other tresholds. Set to zero to disable. By default, this is disabled. (default 200ms)
      --es.bulk.size int                   The number of bytes that the bulk requests can take up before the bulk processor decides to commit (default 5000000)
      --es.bulk.workers int                The number of workers that are able to receive bulk requests and eventually commit them to Elasticsearch (default 1)
      --es.max-span-age duration           The maximum lookback for spans in ElasticSearch (default 72h0m0s)
      --es.num-replicas int                The number of replicas per index in ElasticSearch (default 1)
      --es.num-shards int                  The number of shards per index in ElasticSearch (default 5)
      --es.password string                 The password required by ElasticSearch
      --es.server-urls string              The comma-separated list of ElasticSearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
      --es.sniffer                         The sniffer config for ElasticSearch; client uses sniffing process to find all nodes automatically, disable if not required
      --es.username string                 The username required by ElasticSearch
  -h, --help                               help for jaeger-query
      --log-level string                   Minimal allowed log Level. For more levels see https://github.com/uber-go/zap (default "info")
      --metrics-backend string             Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
      --metrics-http-route string          Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
      --query.health-check-http-port int   The http port for the health check service (default 16687)
      --query.port int                     The port for the query service (default 16686)
      --query.prefix string                The prefix for the url of the query service (default "api")
      --query.static-files string          The path for the static assets for the UI (default "jaeger-ui-build/build/")
      --query.ui-config string             The path to the UI configuration file in JSON format
      --span-storage.type string           Deprecated; please use SPAN_STORAGE_TYPE environment variable

Use "jaeger-query [command] --help" for more information about a command.
```

And with `memory`:

```
$ SPAN_STORAGE_TYPE=memory go run ./cmd/query/main.go help
Jaeger query service provides a Web UI and an API for accessing trace data.

Usage:
  jaeger-query [flags]
  jaeger-query [command]

Available Commands:
  env         Help about environment variables
  help        Help about any command
  version     Print the version

Flags:
      --config-file string                 Configuration file in JSON, TOML, YAML, HCL, or Java properties formats (default none). See spf13/viper for precedence.
  -h, --help                               help for jaeger-query
      --log-level string                   Minimal allowed log Level. For more levels see https://github.com/uber-go/zap (default "info")
      --metrics-backend string             Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
      --metrics-http-route string          Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
      --query.health-check-http-port int   The http port for the health check service (default 16687)
      --query.port int                     The port for the query service (default 16686)
      --query.prefix string                The prefix for the url of the query service (default "api")
      --query.static-files string          The path for the static assets for the UI (default "jaeger-ui-build/build/")
      --query.ui-config string             The path to the UI configuration file in JSON format
      --span-storage.type string           Deprecated; please use SPAN_STORAGE_TYPE environment variable

Use "jaeger-query [command] --help" for more information about a command.
```

**Comment by yurishkuro** [comment] 2018-03-09 15:15
This is by design - why do you think it's confusing? what would you prefer instead?

we used to display all options at once, but that approach simply doesn't work if we want to support dynamic plugins.

**Comment by jpkrohling** [comment] 2018-03-09 15:50
I ran `go run ... help` and expected to see the storage options for Elasticsearch. @kevinearls did the same, expecting the same, so, it's not only me that has the expectation of seeing ES options when running a naked help command :) 

Perhaps it would help to *not* default to Cassandra, providing a hint instead? Like, "to see storage options, set SPAN_STORAGE_TYPE`"

**Comment by yurishkuro** [comment] 2018-03-09 16:33
Yes, I don't see a strong reason why we need to default to Cassandra

**Comment by yurishkuro** [comment] 2018-06-29 22:22
BTW, I noticed that cobra doesn't seem to like the storage type switch when running `help` command.

**Comment by jpkrohling** [comment] 2018-07-02 10:35
> BTW, I noticed that cobra doesn't seem to like the storage type switch when running help command.

What do you mean?

**Comment by yurishkuro** [comment] 2018-07-02 14:32
I wanted to see all storage options so I ran help command while specifying storage type on the cmd line, and it wouldn't work. But if replaced help with -h then it worked. That's inconsistent.

**Comment by jpkrohling** [comment] 2019-04-03 13:48
I'm marking this as a bug, as at least the `help` and `-h` should be consistent. Ideally, we would see all options if no storage is specified. If a storage is specified, only options related to that specific option should be returned.

**Comment by yurishkuro** [comment] 2024-02-03 20:34
will be fixed in v2

**Closed by yurishkuro** 2024-02-03 20:34 UTC
