### ISSUE TITLE
kafka json format data have no refType

### ISSUE THREAD

**Issue by daxwang** [jaegertracing/jaeger#1130] opened 2018-10-19 03:10 UTC
hi, run the jaeger demo,  set SPAN_STORAGE_TYPE=kafka  and --kafka.encoding json, then i consume kafka message, found no refType field in references, it's a bug?
here one jaeger record such as:

{u'traceId': u'AAAAAAAAAAAEOiuLLCuCxQ==', u'process': {u'serviceName': u'frontend', u'tags': [{u'vStr'    : u'Go-2.14.0', u'key': u'jaeger.version'}, {u'vStr': u'xxxx', u'key': u'hostname'}, {u'vStr': u'10.10.0.0', u'key': u'ip'}, {u'vStr': u'177b325d85efd0d5', u'key': u'client-uuid'}]}, u'operationName': u'HTTP GET: /route',     u'flags': 1, u'references': [{u'spanId': u'BDoriywrgsU=', u'traceId': u'AAAAAAAAAAAEOiuLLCuCxQ=='}], u'startTime': u'2018-10-19T0    2:40:53.309501Z', u'duration': u'0.038920s', u'spanId': u'b2Je/UCPwDo='}

**Comment by black-adder** [comment] 2018-10-19 03:17
That is odd. Can you provide us a code snippet to reproduce? Are you able to confirm whether the span had the `refType` before it was encoded and written to kafka?

**Comment by daxwang** [comment] 2018-10-19 04:06
> That is odd. Can you provide us a code snippet to reproduce? Are you able to confirm whether the span had the `refType` before it was encoded and written to kafka?

I'm confirm jaeger collector reporter json format data to kafka has no `refType` ,
![image](https://user-images.githubusercontent.com/19586089/47197230-6a323d80-d397-11e8-8c0a-5413ca784ba7.png)

**Comment by black-adder** [comment] 2018-10-19 14:43
Interesting, are you also able to see if the refType exists when the data is first consumed by the collector? I'm trying to narrow down if this is a collector issue or a go-client issue.

**Comment by yurishkuro** [comment] 2018-10-25 13:46
My guess is that child-of type has value 0 in proto, and we set the json encoding to omit files with zero values. You should see the same behavior with tags where tag type is often omitted since string type is mapped to 0. This was done intentionally to reduce the size of json, but open to discussion.

**Comment by wuyupengwoaini** [comment] 2019-04-24 02:40
I also meet the same problem.Is there a plan to fix it ?

**Comment by yurishkuro** [comment] 2019-04-24 03:22
the data is valid according to the proto schema (refType is optional, default = childOf)

**Comment by pavolloffay** [comment] 2020-07-14 11:49
I am closing this as it is tagged as a question and there is no further activity. 

The JSON parsing would have to make sure that missing fields are unmarshalled as empty/nil properties.

**Closed by pavolloffay** 2020-07-14 11:49 UTC
Labels: question
