### ISSUE TITLE
HTTP Error: Converting JSONSpan to domain Span failed

### ISSUE THREAD

**Issue by massimopacini** [jaegertracing/jaeger#1960] opened 2019-12-03 10:48 UTC
Hello,
Sometimes on some span the ui is replying with a status 500 error

Status | 500
-- | --
Status text | Internal Server Error
URL | /api/traces
Query | end=1575368774721000&limit=20&lookback=1h&maxDuration&minDuration&service=**********&start=1575365174721000
Response body | {   "data": null,   "total": 0,   "limit": 0,   "offset": 0,   "errors": [     {       "code": 500,       "msg": "Converting JSONSpan to domain Span failed: encoding/hex: invalid byte: U+002E '.'"     }   ] }

![Screenshot from 2019-12-03 11-41-15](https://user-images.githubusercontent.com/58468006/70044364-822c4700-15c2-11ea-9291-ed7a4237b89e.png)

For info we are using elk to store span data

**Comment by yurishkuro** [comment] 2019-12-03 15:44
This is a backend issue. Can you try to load the spans for this trace directly from ES and attach JSON?

**Comment by pavolloffay** [comment] 2019-12-04 09:32
This seems to be a duplicate of https://github.com/jaegertracing/jaeger/issues/1926. 

@massimopacini JSON will help us to resolve this issue.

**Comment by massimopacini** [comment] 2019-12-04 09:48
This is the log from the console from jaeger-query: v1.14.0

{"level":"error","ts":1575368745.5988796,"caller":"app/http_handler.go:410","msg":"HTTP handler, Internal Server Error","error":"Converting JSONSpan to domain Span failed: encoding/hex: invalid byte: U+002E '.'","errorVerbose":"encoding/hex: invalid byte: U+002E '.'\nConverting JSONSpan to domain Span failed\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanReader).collectSpans\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go:221\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanReader).multiRead\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go:355\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanReader).FindTraces\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go:280\ngithub.com/jaegertracing/jaeger/storage/spanstore/metrics.(*ReadMetricsDecorator).FindTraces\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/storage/spanstore/metrics/decorator.go:79\ngithub.com/jaegertracing/jaeger/cmd/query/app/querysvc.QueryService.FindTraces\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/querysvc/query_service.go:88\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).search\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:203\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1878\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleError\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:410\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).search\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:204\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:132\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/mux/mux.go:212\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1995\ngithub.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/gorilla/handlers/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/net/http/server.go:1878"}

**Comment by pavolloffay** [comment] 2019-12-04 09:54
@massimopacini we need span JSON stored in Elasticsearch. The logs do not show the data causing the issue.

You can get the data by querying elasticsearch https://github.com/jaegertracing/jaeger/issues/1926#issuecomment-559852808

**Comment by massimopacini** [comment] 2019-12-04 09:55
I'm trying to find the segment causing the issue as traceID is not refered in the log

**Comment by pavolloffay** [comment] 2019-12-04 10:01
From the log `Converting JSONSpan to domain Span failed: encoding/hex:`it seems that the problematic part is either tag or log with binary type 
https://github.com/jaegertracing/jaeger/blob/343fcc6ddd3bdb94dec864bddc2ff8794d6666a8/plugin/storage/es/spanstore/dbmodel/to_domain.go#L229 (hex lib is used only for binary annotation)

You should be able to find that tag in Elasticsearch. The type will be set to `4` or will have binary in the name.

**Comment by pavolloffay** [comment] 2019-12-04 10:02
Alternativey if the instrumentation is small try to find where you use binary tag and get the value from there.

**Comment by massimopacini** [comment] 2019-12-04 10:11
Yes I found it ;) 

`{
  "_index": "jaeger-span-2019-12-03",
  "_type": "span",
  "_id": "chw2y24B83Q9Z-Nk8mv3",
  "_version": 1,
  "_score": 0,
  "_source": {
    "traceID": "f30e6283a8829f8b",
    "spanID": "c6a389b7beecb804",
    "flags": 1,
    "operationName": "/*****/***",
    "references": [
      {
        "refType": "CHILD_OF",
        "traceID": "f30e6283a8829f8b",
        "spanID": "7a5fadef28a475fd"
      }
    ],
    "startTime": 1575367405662000,
    "startTimeMillis": 1575367405662,
    "duration": 22000,
    "tags": [],
    "tag": {
      "http_header_accept": "*/*",
      "http_header_accept-encoding": "gzip, deflate, br",
      "http_header_accept-language": "en-us",
      "http_header_content-length": "363",
      "http_header_content-type": "application/xml",
      "http_header_uber-trace-id": "f30e6283a8829f8b:7a5fadef28a475fd:914f151e851cd71d:1",
      "http_header_x-envoy-downstream-service-cluster": "",
      "http_header_x-envoy-expected-rq-timeout-ms": "15000",
      "http_header_x-envoy-internal": "true",
      "http_header_x-forwarded-proto": "http",
      "http_header_x-request-id": "163e6ec7-72f3-96d7-b465-889bd8da7e53",
      "http_header_x-voo-customerid": "0021745343",
      "http_header_x-voo-groupid": "8",
      "http_header_x-voo-jsessionid": "D99CB29A205FF27582EBB4DFB9E8CF96.U04",
      "http_header_x-voo-srp": "c453252eb9e3",
      "http_status_code": 200,
      "internal_span_format": "jaeger"
    },
    "logs": [
      {
        "timestamp": 1575367405663000,
        "fields": [
          {
            "key": "requestedBody",
            "type": "binary",
            "value": "3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d227574662d38223f3e0a3c5265717565737420786d6c6e733d2275726e3a6576656e7469733a7472617869737765623a312e30223e0a202020203c4964656e746974793e0a20202020202020203c50726f66696c6549643e35386366343939662d356339662d343562372d623735342d6661623838633261353230337e7e32334d617374657250726f66696c653c2f50726f66696c6549643e0a202020203c2f4964656e746974793e0a202020203c526f6f7452656c6174696f6e51756572792072656c6174696f6e4e616d653d2243706573223e0a20202020202020203c4f707469..."
          }
        ]
      }
    ],
    "process": {
      "serviceName": "*******",
      "tags": [],
      "tag": {
        "*****_version": "3.0.0",
        "client-uuid": "b569c83e-6612-48d0-b5dc-cca3f078134a",
        "hostname": "b059c0fc2365",
        "ip": "10.0.101.22",
        "jaeger_version": "Node-3.17.0"
      }
    }
  },
  "fields": {
    "startTimeMillis": [
      "2019-12-03T10:03:25.662Z"
    ]
  },
  "highlight": {
    "operationName": [
      "@kibana-highlighted-field@/****/***@/kibana-highlighted-field@"
    ]
  }
}`

**Comment by pavolloffay** [comment] 2019-12-04 10:25
Did you cut the end? Because there are `...` at the end.

**Comment by pavolloffay** [comment] 2019-12-04 10:27
How do you add the value of `requestedBody` field?

**Comment by massimopacini** [comment] 2019-12-04 10:47
@pavolloffay no I haven't touch that one it was already like that maybe somewhere cut by node libs.

for that I'm doing a

span.log({
                    'requestedBody': req.body
                });

Body is coming from Restify and it could be a bin

**Comment by pavolloffay** [comment] 2019-12-04 13:43
Alright, I found the issue. 

If the length of binary array is longer than 256, the array is stripped and added `...` at the end. This is stored to ES and at query time `hex.DecodeString` fails because of the dots.

@yurishkuro why the binary array is stripped? 

Cassandra uses correct value https://github.com/jaegertracing/jaeger/blob/343fcc6ddd3bdb94dec864bddc2ff8794d6666a8/plugin/storage/cassandra/spanstore/dbmodel/converter.go#L195. The stripped value is used only when indexing. ES and badger use `ToString` which seems like a bug.

**Comment by yurishkuro** [comment] 2019-12-04 16:35
> If the length of binary array is longer than 256, the array is stripped and added ... at the end.

Do we know where this happens?  Typically tag value trimming happened in the clients.

**Comment by pavolloffay** [comment] 2019-12-04 16:49
@massimopacini is using jaeger node client. Not sure if he disabled trimming or it's not applied by default.

**Comment by yurishkuro** [comment] 2019-12-05 06:08
I don't believe Node client has any truncation logic.

**Closed** 2019-12-11 09:37 UTC
Labels: bug, elasticsearch
