### ISSUE TITLE
Jaeger v2 based on OpenTelemetry collector

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#3500] opened 2022-01-28 13:18 UTC
## Update (Sept 2023)

Superseded by #4843

---

## Proposal (2022)

Creating top-level issue for Jaeger v2 based on OpenTelemetry collector. 

This has already been discussed a couple of times:
* roadmap https://www.jaegertracing.io/roadmap/#Integration%20with%20OpenTelemetry%20collector 
* two prototypes https://github.com/jaegertracing/jaeger/tree/v1.22.0/cmd/opentelemetry and https://github.com/jaegertracing/jaeger-otelcol. Docs https://www.jaegertracing.io/docs/1.20/opentelemetry/
* Many issue from: https://github.com/jaegertracing/jaeger/issues?q=is%3Aissue+opentelemetry+is%3Aclosed

I would like to bring the topic back as I think it is vital for the future success of Jaeger and staying relevant. Since we worked on v2 a couple of things changed, and therefore, I have created a new proposal on how v2 could be designed https://docs.google.com/document/d/1d7j956tDVYacKHF-l0JL9sVhpbYkt0JECDyGeup-olc/edit?usp=sharing and what is the impact on the ecosystem. 

I would like to open this for discussion.  If you are Jaeger user please upvote the issue if you would like the proposal including the breaking changes and impact on deployment helm/operator.

**Comment by eugeniyk** [comment] 2022-01-28 15:53
Direction wise makes total sense as jaeger pipeline looks rudimentary, however I believe there are some features that are not yet avail in otel collectors

What's left to Jaeger then? custom protocol as receiver (which should go away at some point), UI as extension and custom storage integration? Means just coupling querier with particular exporters?

**Comment by pavolloffay** [comment] 2022-01-28 16:09
Jaeger will provide the storage layer and UI. 

Once we are based on the OTEL collector it will be easier to write extensions and provide additional functionality.

**Comment by yurishkuro** [comment] 2022-01-28 17:05
> What's left to Jaeger then?

@eugeniyk Think of this not from the architecture point of view but from the user impact - *everything* about Jaeger is still there, plus some additional capabilities we could inherit from OTEL (the most critical one - OTLP receiver). Jaeger is an end-to-end tracing platform, OTEL collector is not, just a piece of it.

**Comment by jkowall** [comment] 2022-01-29 00:42
So, what about the data model which is used on storage, and how about the terminology in Jaeger would evolve to align with Otel versus OT? I don't think we need to make those changes, but they would help for the future. Unfortunatley they don't really help users so much, but are more for maintainers and the project.

The only other concern is the UI, we haven't been anything really meaningful on the UI side beyond the recent monitoring tab for the last several years. I have been pushing the OpenSearch Dashboards team to add Jaeger format support, they are already working with an OpenTelemetry schema on OpenSearch, but as you know we are on an OT schema for Jaeger which is "legacy". I think we need to address the schema and allow the Jaeger format to be more widely used for UIs which will evolve, as the Jaeger UI is likely to stagnate.

**Comment by pavolloffay** [comment] 2022-01-31 09:51
> So, what about the data model which is used on storage, and how about the terminology in Jaeger would evolve to align with Otel versus OT? I don't think we need to make those changes, but they would help for the future. Unfortunatley they don't really help users so much, but are more for maintainers and the project.

The question I would as here is, what "features" OTEL schema gives compared to Jaeger/OT? They are pretty much interchangeable. The storage layer can change schema independently at any point, it's more like an implementation detail given the scope of this issue. 

> The only other concern is the UI, we haven't been anything really meaningful on the UI side beyond the recent monitoring tab for the last several years. I have been pushing the OpenSearch Dashboards team to add Jaeger format support, they are already working with an OpenTelemetry schema on OpenSearch, but as you know we are on an OT schema for Jaeger which is "legacy". I think we need to address the schema and allow the Jaeger format to be more widely used for UIs which will evolve, as the Jaeger UI is likely to stagnate.

I agree the Jaeger UI needs migration work as weel. At minimum we can start with renaming some UI elements Tags->Attributes etc. and at one point migrate UI to use the Jaeger V3 or other OpenTelemetry compatible model. 

Do you have references to OpenSeach adopting OTEL model? The OTEL JSON is (or was) not stable yet. In the past we had issues in Jaeger when storage layer used directly jaeger model. The separation gives more flexibility and shading from breaking changes.

**Comment by jkowall** [comment] 2022-02-01 18:48
> The question I would as here is, what "features" OTEL schema gives compared to Jaeger/OT? They are pretty much interchangeable. The storage layer can change schema independently at any point, it's more like an implementation detail given the scope of this issue.
> 
Just more about Jaeger being aligned with the current tracing standard versus being aligned with the deprecated tracing standard. The second idea is that if we adopt the Otel schema we could work with OpenSearch Dashboards trace analytics which is using an Otel schema too. More on this in the next paragraph.

> I agree the Jaeger UI needs migration work as weel. At minimum we can start with renaming some UI elements Tags->Attributes etc. and at one point migrate UI to use the Jaeger V3 or other OpenTelemetry compatible model.

Yes.... and more on this below
 
> Do you have references to OpenSeach adopting OTEL model? The OTEL JSON is (or was) not stable yet. In the past we had issues in Jaeger when storage layer used directly jaeger model. The separation gives more flexibility and shading from breaking changes.

Currently, they are using "Data prepper" which does the writing to OpenSearch/ElasticSearch. They are not using Otel collector since they are doing aggregates similar to the spark component in Jaeger. Here is the schema for Data Prepper: https://github.com/opendistro-for-elasticsearch/data-prepper/blob/634a426ef0377ebc2e525e954177b350ebaeabe2/docs/schemas/trace-analytics/otel-v1-apm-span-index-template.md Ideally they will support a Jaeger schema for reading too, but without aggregates there will be a bunch of features that do not work (maps, aggregated metrics, etc).

**Comment by yurishkuro** [comment] 2022-02-01 20:38
> OpenSearch Dashboards trace analytics

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/trace-analytics.html

Fairly primitive so far, but certainly a viable alternative to the Monitor tab (#2954). @jkowall do you know if OS is planning to venture more into trace visualizations like the timeline view, graph view, etc.?

I think this brings one other crucial questions of Jaeger V2 - should we just focus on a single storage backend that can actually provide these analytical capabilities? TBH, it's not clear to me if querying OS for aggregate data is preferable over the Monitoring tab approach of using a metrics system for the same aggregates. It's certainly simpler dealing with just one backend, but likely at the expense of query latency.

**Comment by jkowall** [comment] 2022-02-01 23:57
Still needs work, the plugin is not that old. We had the PM on a Jaeger community call last year. They are planning on timeline and graphical topology. We also want to build metric query capabilities into OpenSearch Dashboards so you can hook it up to a PromQL backend, but no one is actively working on that at this time.

I think less backends is a good move, but I also think that the current backends are not very good with Metrics. I hope there is something better on the horizon that supports PromQL and unstructured data well. Hard to tell what and when that might happen. 

The number of breaking changes coming in v8 will be interesting: https://www.elastic.co/guide/en/elasticsearch/reference/8.0/migrating-8.0.html Welcome to the ongoing Elastic push to break open source and backwards compatibility.

**Comment by albertteoh** [comment] 2022-02-07 08:23
> TBH, it's not clear to me if querying OS for aggregate data is preferable over the Monitoring tab approach of using a metrics system for the same aggregates. It's certainly simpler dealing with just one backend, but likely at the expense of query latency.

Another benefit of the Monitoring tab approach is its tighter integration within Jaeger UI, supporting use cases that rely on  aggregated data to help narrow down the search space to the more "interesting" traces (high latency, error rate traces) with a single button click.

I agree though, that the approach used with the Monitoring tab has quite a few moving parts: OTEL collector with the correct config to perform the aggregation from traces to metrics, a metrics store to persist the metrics, then Jaeger query + UI to visualize the metrics; and like the idea of supporting a single storage backend.

**Comment by pavolloffay** [comment] 2022-02-07 08:37
Jager v2 would reduce the dependency on the OTEL collector for the monitoring feature. We bould include the processor that extracts metrics in the Jaeger main distribution.

**Comment by gai6948** [comment] 2022-02-08 13:52
From a user's perspective, I would like to know what it really means by "Jaeger collector based on Otel collector", is that a drop-in replacement for the Otel collector?

The folks from Dow Jones has written an excellent [blog post](https://opensearch.org/blog/technical-post/2021/12/distributed-tracing-pipeline-with-opentelemetry/) detailing how OS, Jaeger and Otel plays together in enterprise settings, Otel acts as centralized trace pipeline and Jaeger being a sink.

Perhaps Jaeger in the future can remove client libraries/agents and focus on how to deal with the trace data (e.g. adding anomaly detection features?)

On a side note, recent enhancements in Grafana's Jaeger data source plugin are really impressive, not saying that can replace the Jaeger UI, but maybe in the future more users will use Grafana instead of the Jaeger UI.

<img width="1842" alt="Screenshot 2022-02-08 at 9 38 32 PM" src="https://user-images.githubusercontent.com/61444500/153000008-fe3ca6a7-ef57-4454-b460-4d2fe82f7adb.png">

**Comment by jkowall** [comment] 2022-02-09 17:59
> From a user's perspective, I would like to know what it really means by "Jaeger collector based on Otel collector", is that a drop-in replacement for the Otel collector?

It would have some additional exporters or other capabilities the project needs, but otherwise it would be very similar and mostly upstream code.
 
> The folks from Dow Jones has written an excellent [blog post](https://opensearch.org/blog/technical-post/2021/12/distributed-tracing-pipeline-with-opentelemetry/) detailing how OS, Jaeger and Otel plays together in enterprise settings, Otel acts as centralized trace pipeline and Jaeger being a sink.

Problem is that data prepper is a pain to handle since it's doing the same things the collector is doing. Creates a lot of complexity, but yes it can play well, you are duplicating the data twice since it needs to be stored as Data prepper and Jaeger schemas. 

> Perhaps Jaeger in the future can remove client libraries/agents and focus on how to deal with the trace data (e.g. adding anomaly detection features?)

The problem is we'd have to become more opinionated about the backend. The client libraries would be replaced by Otel, in fact they already have been since we deprecated the old ones:  https://www.jaegertracing.io/docs/1.30/client-libraries/

> On a side note, recent enhancements in Grafana's Jaeger data source plugin are really impressive, not saying that can replace the Jaeger UI, but maybe in the future more users will use Grafana instead of the Jaeger UI.

The problem is that Grafana's licensing is not friendly to CNCF, and in the future I wouldn't be surprised to see an Elastic move pulled creating a gap in the Prometheus community and potentially a gap in Jaeger. I prefer to see an Apache 2.0 licensed solution like OpenSearch Dashboards or Apache Superset.

**Comment by pavolloffay** [comment] 2022-05-09 17:24
I have some good news for this ticket! 

I have created https://github.com/jaegertracing/jaeger-opentelemetry-collector to bootstrap the work on the jaeger v2/ rebase on top of the OpenTelemetry collector. It is a community project, anybody interested can start contributing by migrating Jaeger storage implementations as exporters.

**Comment by issraee** [comment] 2022-08-05 14:53
Hello, I'm trying to send trace data of a wordpress website to opensearch through jaeger. I'm using wordpress plugin wordpress to send the data to jaeger, and from there to opensearch :

docker run --rm -it -v ${PWD}:/config \
-e SPAN_STORAGE_TYPE=elasticsearch opensearchproject/opensearch\
jaegertracing/jaeger-opentelemetry-collector \
--config-file=/config/config.yaml \
--es.server-urls=http://IP:9200/ \
--es.num-shards=3

With config.yaml :

exporters:
otlp/data-prepper:
endpoint: http://data-prepper:9200
insecure: true
processors:
attributes:
actions:
- key: user
action: delete
service:
pipelines:
traces:
processors: [attributes]

-> It gives the following error

 ./[opensearch-docker-entrypoint.sh](http://opensearch-docker-entrypoint.sh/): line 140: /usr/share/opensearch/jaegertracing/jaeger-opentelemetry-collector: No such file or directory

I'm looking for this since using open telemetry seperately and data prepper is returning connection errors/no valid pipeline for execution. So if this works it would simplify the process so much. Any suggestions to discuss would be appreciated.

**Comment by yurishkuro** [comment] 2022-08-05 14:59
> jaegertracing/jaeger-opentelemetry-collector

where are you getting instructions to use this ^ name? If your Wordpress installation exports OpenTelemetry data, you can send it to regular Jaeger collector: https://medium.com/jaegertracing/introducing-native-support-for-opentelemetry-in-jaeger-eb661be8183c

**Comment by derek-ho** [comment] 2022-12-28 14:53
Hey folks @pavolloffay @yurishkuro @gai6948 @eugeniyk @albertteoh @issraee,

I've been working on jaeger integration with OpenSearch Dashboards Trace Analytics. Here's a quick demo, can you folks let me know what you think of it? We are hoping to get this into the next release, but would definitely like to hear some feedback about it from the community on what is useful/could be improved from end users and work with the Jaeger community to drive future development. 

https://github.com/opensearch-project/observability/issues/755#issuecomment-1366696993

The github issue tracking some of the PM/UI/UX work is here: https://github.com/opensearch-project/observability/issues/755. 

Caveat: This demo is made from jaeger data ingested in a specific format that is more friendly to opensearch:
```--es.tags-as-fields.all=true```. It doesn't work well if it is not ingested in this format, we may want to bring this up to the community or make this the default, since it is not today. Any thoughts on this?

**Comment by yurishkuro** [comment] 2023-09-24 02:16
For people subscribing to this issue - I have a new PR that I'd like to get feedback on. It currently implements a working all-in-one on top of OTEL Collector framework. https://github.com/jaegertracing/jaeger/pull/4766/

**Comment by yurishkuro** [comment] 2023-10-15 04:19
I am closing this in favor of a new issue where the actual roadmap is tracked. 

https://github.com/jaegertracing/jaeger/issues/4843

**Closed by yurishkuro** 2023-10-15 04:19 UTC
Labels: area/otel
