### ISSUE TITLE
Flaky test TestGRPCResolverRoundRobin (again)

### ISSUE THREAD

**Issue by esnible** [jaegertracing/jaeger#3548] opened 2022-02-24 05:49 UTC
This is a repeat of #2085 and #2674.

TestGRPCResolverRoundRobin fails 100% of the time on my Mac (macOS Monterey 12.2.1) when run using `time go test -tags=memory_storage_integration ./pkg/discovery/...`.

The test is flaky in two ways.

I was able to cure both problems, but I don't understand my fixes, and thus am not confident enough to create a PR around them (yet).

Rarely the test fails with a panic on `addrs[p.Addr.String()] = struct{}{}`.  This is likely because p.Addr is set with `grpc.Peer()`, which populates the peer field *after* the RPC completes based on the `Context`.  We are using a non-blocking Client, and re-using the same Context for each connection.  Something is racing in there.  Wrapping the statement with `if p.Addr != nil {` removes the occasional panic, but I am unsure if it is safe to use `grpc.Peer()` at all if work might be done on another thread.

I noticed `makeSureConnectionsUp()` has the comment `// 3000 * 10ms = 30s` but the test fails in under 2s.  Adding `time.Sleep(10 * time.Millisecond)` before `continue` to make the comment true fixes the test.  (The problem also goes away if I raise 3000 to 2000.)

**Comment by yurishkuro** [comment] 2024-01-09 19:25
@tarhphilomina feel free

**Comment by tarhphilomina** [comment] 2024-01-11 23:54
I am so sorry , I can't reproduce this error.  I just realized the error occurs only on Mac , I work with ubuntu. i am sorry. I won't be able to handle this issue.
![image](https://github.com/jaegertracing/jaeger/assets/156124227/40fbcf65-133e-4d24-8fce-415fd004664a)

**Comment by yurishkuro** [comment] 2024-01-12 01:03
@tarhphilomina no worries. fwiw I don't think the test failure is really dependent on Mac vs Linux, from the description (and the fact that adding sleep fixes it) it sounds like a race condition, perhaps more rare on some architectures. I could not reproduce it with 100 runs
```
$ go test -count 100 ./pkg/discovery/...
ok  	github.com/jaegertracing/jaeger/pkg/discovery	0.162s
ok  	github.com/jaegertracing/jaeger/pkg/discovery/grpcresolver	2.283s
```

Also, `-tags=memory_storage_integration` has no bearing on the test, this build tag is not used in `./pkg/discovery/...`. 

Overall, this is a pretty old ticket and I do not recall this test failing too recently, it may have been fixed or the race went away from upgrading grpc. I am closing it.

**Closed by yurishkuro** 2024-01-12 01:03 UTC
Labels: bug, help wanted, good first issue
