### ISSUE TITLE
how to remove internal.span.format="jaeger"

### ISSUE THREAD

**Issue by zheyiyi** [jaegertracing/jaeger#1830] opened 2019-10-04 15:02 UTC
In the jaeger Ui, the tag include  internal.span.format ="jaeger", is it possible to remove it? Where is the place it is added

**Comment by vprithvi** [comment] 2019-10-04 15:09
What issue is this tag causing for you?

**Comment by zheyiyi** [comment] 2019-10-04 17:21
No issue.  just want to remove it from tag. it is useless for my appliction

Prithvi Raj <notifications@github.com> 于2019年10月4日周五 上午11:09写道：

**Comment by jpkrohling** [comment] 2019-10-07 15:48
Would it be sufficient to suppress the UI from displaying it, or are you looking to avoid even adding this tag to the span being reported?

**Comment by jpkrohling** [comment] 2019-10-07 15:48
(btw, I'm quite sure this is added in the backend...)

**Comment by pavolloffay** [comment] 2019-10-09 12:23
It is added in Jaeger collector `https://github.com/pavolloffay/jaeger/blob/343fcc6ddd3bdb94dec864bddc2ff8794d6666a8/cmd/collector/app/span_processor.go#L160. `

If there is no valid use case to hide it or remove it we will probably close this ticket. Other Jaeger components can rely on this tag while doing another processing. It was added as https://github.com/jaegertracing/jaeger/issues/1490.

**Comment by smanolloff** [comment] 2020-05-07 14:07
I agree with @zheyiyi -- having this appear among other (user-defined) tags is actually undesirable. Internal tags have no place in the UI, unless specifically enabled for debugging purposes.

**Comment by yurishkuro** [comment] 2020-05-07 15:57
We can either have configuration for the UI to hide some tags, or have an option in the collector to not add these tags if people don't want them.

**Comment by smanolloff** [comment] 2020-05-08 08:50
Hiding tags in the UI, is fine by me (eg. with regex).

**Comment by apm-opentt** [comment] 2020-05-08 10:45
The internal.span.format ="jaeger" tag actually helps me in debugging.  Our Jaeger collector receives Jaeger spans and Zipkin spans.  With the internal.span.format I can see at a glance in Jaeger UI whether the span came from Jaeger or Zipkin.  It is very useful.  Please keep it.

**Comment by yurishkuro** [comment] 2020-05-08 14:35
@apm-opentt same here, that's why we added it.

**Comment by pavolloffay** [comment] 2020-05-11 08:27
Note that this tag is not being added in Jager OTEL components. It's only added in collector's processors which are not being used in OTEL. 

I find the tag useful to understand the instrumentation layer. Perhaps we could add this to OTEL spec and then use OTEL attribute processor to remove the label https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor#attributes. However, the processor does not work on resource/process objects. Perhaps we could extend it to support this feature.

**Comment by ndrwrbgs** [comment] 2020-06-21 19:07
I'd like to be able to configure the visibility of the tag in the UI. While it's useful for me, like previous commenters on this thread, as the tracing implementor, I think it's distracting from the content for my consumers (developer peers).

**Comment by cptkng23** [comment] 2021-02-18 21:33
Is there any update on how to remove this tag. Be it UI or collector?

**Comment by kgunnerud** [comment] 2022-10-13 13:38
Would be nice if it could be configured for example by using the --query.ui-config file. For us, it would be nice to hide a few selected tags that as of now give us little to no benefits

**Comment by yurishkuro** [comment] 2022-10-13 14:45
`--query.ui-config` is one option but it means the data would still be returned to the UI and just not displayed. Another alternative is a cli flag to the query service to suppress returning certain tags in the JSON response (may be easier to implement).

**Comment by pmuls99** [comment] 2023-08-07 10:04
> `--query.ui-config` is one option but it means the data would still be returned to the UI and just not displayed. Another alternative is a cli flag to the query service to suppress returning certain tags in the JSON response (may be easier to implement).

This way of implementing it feels right! As the problem is still prominent, can I go ahead with the implementation @yurishkuro.

**Comment by yurishkuro** [comment] 2024-08-03 17:45
Closing since nobody feels strongly enough to provide a fix and this won't be present in jaeger-v2 anyway

**Closed by yurishkuro** 2024-08-03 17:45 UTC
Labels: help wanted, good first issue, fixed-in-v2
