### ISSUE TITLE
Queries with operation and tags fail with Cassandra as storage

### ISSUE THREAD

**Issue by kevinearls** [jaegertracing/jaeger#768] opened 2018-04-06 09:30 UTC
I have a test which creates traces like the one listed below.   Queries which contain both an operation and one or more tags, like these

-- curl "jaeger-query-myproject.192.168.64.4.nip.io/api/traces?service=standalone&tag=iteration:1&operation=Thread96"

work correctly if I'm using ElasticSearch as storage, but with Cassandra no data is returned.  (Note the query will work correctly with just the operation or just the tag.)

{
  "data": [
    {
      "traceID": "54d50b2b566d7d93",
      "spans": [
        {
          "traceID": "54d50b2b566d7d93",
          "spanID": "54d50b2b566d7d93",
          "flags": 1,
          "operationName": "Thread96",
          "references": [
            
          ],
          "startTime": 1.522916908365e+15,
          "duration": 100210,
          "tags": [
            {
              "key": "sampler.type",
              "type": "string",
              "value": "probabilistic"
            },
            {
              "key": "sampler.param",
              "type": "float64",
              "value": 1
            },
            {
              "key": "podname",
              "type": "string",
              "value": "llc82"
            },
            {
              "key": "iteration",
              "type": "int64",
              "value": 1
            }
          ],
          "logs": [
            
          ],
          "processID": "p1",
          "warnings": null
        }
      ],
      "processes": {
        "p1": {
          "serviceName": "standalone",
          "tags": [
            {
              "key": "hostname",
              "type": "string",
              "value": "jaeger-standalone-performance-tests-llc82"
            },
            {
              "key": "ip",
              "type": "string",
              "value": "172.17.0.4"
            },
            {
              "key": "jaeger.version",
              "type": "string",
              "value": "Java-0.26.0"
            }
          ]
        }
      },
      "warnings": null
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": null
}

**Comment by yurishkuro** [comment] 2018-11-10 16:51
Duplicate of #166

**Closed by yurishkuro** 2018-11-10 16:51 UTC
Labels: duplicate
