### ISSUE TITLE
 Is `:` forbidden in service name?

### ISSUE THREAD

**Issue by xvdy** [jaegertracing/jaeger#1932] opened 2019-11-19 12:03 UTC
## Requirement - what kind of business use case are you trying to solve?

jaeger-1.14.0-linux-amd64, es 7.4 as storage.
## Problem - what in Jaeger blocks you from solving the requirement?

If service name includes  `:`  , the service could not be search from /api/services.
I try to use `.`, `#`, `/` as a part of service name, all works well. 
Is `:` forbidden in service name?

**Comment by yurishkuro** [comment] 2019-11-19 17:43
I don't think anything in Jaeger explicitly prohibits it, but it may be the side effect of Elastic query language.

cc @pavolloffay

**Comment by xvdy** [comment] 2019-11-20 01:25
New findings. If I use jaeger agent to receive spans, the service name including `:` also works well. When I send spans directly to collector by http, the things go wrong. Service name including `:` couldn't be sent to collector directly by http.

**Comment by jpkrohling** [comment] 2019-11-20 09:08
Looks like it might indeed be a problem with ES, as I got a simple example to work with in-memory:

![image](https://user-images.githubusercontent.com/13387/69224892-9b260880-0b7d-11ea-8d1e-f590c044ce80.png)

@xvdy, are you using Elasticsearch as the storage? Are you able to the in-memory storage instead, just to check whether it's storage-related?

**Comment by xvdy** [comment] 2019-11-20 12:36
When I use es as backend storage and send spans to local jaeger agent, It works well.
When I use es as backend storage and send spans to collector by http directly, It went wrong.

**Comment by jpkrohling** [comment] 2019-11-20 13:27
Works for me with the Java client and Elasticsearch 6.8.4 and 7.4.2:

```console
$ podman pod create --publish 16686 --publish 14268 --name issue-1932
$ podman create --pod issue-1932 --name elasticsearch --expose 9200 -e "discovery.type=single-node" elasticsearch:6.8.4
$ podman create --pod issue-1932 --name jaeger-all-in-one --expose 16686 --expose 14268 --restart always -e SPAN_STORAGE_TYPE=elasticsearch jaegertracing/all-in-one:1.15 
$ podman pod start issue-1932
```

On the [client side](https://github.com/jpkrohling/devoxx19-demo/tree/master/service-mesh-order) (`JAEGER_ENDPOINT="http://127.0.0.1:14268/api/traces" JAEGER_SERVICE_NAME="myservice:name" mvn quarkus:dev`):
```
2019-11-20 14:20:26,498 INFO  [io.jae.Configuration] (executor-thread-1) Initialized tracer=JaegerTracer(version=Java-0.34.0, serviceName=myservice:name, reporter=RemoteReporter(sender=HttpSender(), closeEnqueueTimeout=1000), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=caju, jaeger.version=Java-0.34.0, ip=192.168.0.13}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)
```

![image](https://user-images.githubusercontent.com/13387/69242449-28c71f80-0ba1-11ea-95a0-953132c42786.png)

**Comment by pavolloffay** [comment] 2019-11-29 16:11
@xvdy It seems that @jpkrohling wasn't able to reproduce your issue. 

Maybe you didn't configure Jaeger HTTP URL in the client correctly? 

Anyways I will close this issue. If you have still have the problem please comment here. It would laso help if you could provide jaeger tracer configuration and the exact string of the service name.

**Closed by pavolloffay** 2019-11-29 16:11 UTC
Labels: elasticsearch
