### ISSUE TITLE
[cassandra] does not handle limit parameter correctly

### ISSUE THREAD

**Issue by trtg** [jaegertracing/jaeger#411] opened 2017-09-20 23:02 UTC
I originally opened this on jaeger-ui [here](https://github.com/uber/jaeger-ui/issues/52) , but it seems the issue is in the rest API itself or something lower level than that

 if i use the stock docker image for jaeger-query using the docker-compose setup below, I see the following reproducible behavior: clicking "find traces" while 'all' is selected will show 2 results, if the result limit is set to any value between 1 and 11. If I set the limit to a value between 12 and 22, I see 2 results. If the limit is between 23 and 34, I see 3 results. If the limit is 35 to 45, I see 4 results. If instead of "all" I pick any other operation name, I can see all the results.

`

jaeger_query:
image: jaegertracing/jaeger-query
dns:
- 8.8.8.8
- 8.8.4.4
command: /go/bin/query-linux --query.static-files=/go/jaeger-ui/ --cassandra.keyspace jaeger_v1_datacenter1 --cassandra.servers cassandra.internal --cassandra.connections-per-host 2 --query.port 8380
ports:
- 8380:8380

**Comment by jpkrohling** [comment] 2017-09-21 10:53
Looks like there's a formatting error on the docker compose part. Would it be possible to fix it? It would also be helpful to have a couple of screenshots demonstrating what you are experiencing.

**Comment by trtg** [comment] 2017-10-13 05:32
@jpkrohling did further investigation and compiled the screenshots.

so, doing a little more digging there seem to be a lot of issues when combining different query parameters in the jaeger UI. If you leave min and max duration blank, set operation name to all, and limit 
to 11 you get back only 2 results:
[https://imgur.com/gallery/OAI8R](url)

if you leave min and max duration blank, set operation name to all, and limit to 20, you get back only 3 results, as in this screen shot:
[https://imgur.com/gallery/i7AJr](url)

if you leave min and max duration blank, set operation name to all, and limit to 23, you get back only 4 results, as in this screen shot:
[https://imgur.com/gallery/63ThF](url)

BUT, if you set max duration to 900ms, set operation name to all, and limit to 20, you get back 20 results, some of which vastly exceed the max duration that was specified:
[https://imgur.com/gallery/HuhGO](url)

**Comment by yurishkuro** [comment] 2018-11-10 16:48
Duplicate of #166

**Closed** 2018-11-10 16:48 UTC
Labels: duplicate
