### ISSUE TITLE
Elasticsearch: incomplete first trace in new daily index

### ISSUE THREAD

**Issue by fthiel** [jaegertracing/jaeger#1063] opened 2018-09-18 10:54 UTC
## Requirement - what kind of business use case are you trying to solve?

- using jaeger, elasticsearch with daily automatically created indices and kibana for logging
- java test application that produces one trace with several spans every 5 minutes
- there are some sub spans that are started and closed in parallel threads

## Problem - what in Jaeger blocks you from solving the requirement?

All but one span are missing in the first trace of a new daily index. And this span is not the first or the last but some span in between.

**Comment by fthiel** [comment] 2018-09-19 07:34
yesterday i manually created the index for today and let the test application run again and no spans got lost, that confirms it has something to do with the automatic creation of a new index

**Comment by pavolloffay** [comment] 2018-09-19 08:14
@fthiel thanks for reporting we will have a look

**Comment by fthiel** [comment] 2018-10-01 06:47
Hi,
could you achieve any progress here? @pavolloffay

**Comment by pavolloffay** [comment] 2018-10-03 09:03
@fthiel I failed to reproduce. Could  you please clarify:
* what ES version are you using?
* number of jaeger collectors
* are you reporting spans to collector or agent?

If you can share a reproducer that would be the best.

**Comment by fthiel** [comment] 2018-10-05 10:05
- ElasticSearch 6.3.2
- one jaeger collector
- we report spans to the collector

Can this be related to the version we have for the collector and agent? These are jaeger-collector:1.2.0 and jaeger-agent:1.2.0. We will try to upgrade it to 1.7 next week and test this again.

**Comment by pavolloffay** [comment] 2018-10-05 14:05
@fthiel do you see a similar error in your logs?

```
{"level":"error","ts":1538747963.7151263,"caller":"app/span_processor.go:102","msg":"Failed to save span","error":"Failed to create index: elastic: Error 400 (Bad Request): index [jaeger-span-2018-10-05/wIcfjO5ZQyyYeMNeoGpIBQ] already exists [type=resource_already_exists_exception]","errorVerbose":"elastic: Error 400 (Bad Request): index [jaeger-span-2018-10-05/wIcfjO5ZQyyYeMNeoGpIBQ] already exists [type=resource_already_exists_exception]\nFailed to create index\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:191\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:152\ngithub.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:123\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:101\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:125\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65\nruntime.goexit\n\t/home/ploffay/bin/go/src/runtime/asm_amd64.s:2361","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:88\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:125\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:56\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"}
```

This has been fixed in https://github.com/jaegertracing/jaeger/pull/921 and released in 1.6. Please try to update and let us know.

**Comment by pavolloffay** [comment] 2018-10-09 09:54
@fthiel I will close this. If the issue is still there after update please comment/reopen.

**Closed by pavolloffay** 2018-10-09 09:54 UTC
Labels: elasticsearch

**Comment by fthiel** [comment] 2018-10-25 05:40
just if someone else gets this problem: updating jaeger to 1.7 solved this
