### ISSUE TITLE
Document HTTP endpoints in query and collector services

### ISSUE THREAD

**Issue by badiib** [jaegertracing/jaeger#158] opened 2017-05-12 17:49 UTC
We don't really define our API anywhere, and we should do so. This is probably a good issue to bring up the idea of using swagger for self-documentation.

**Comment by yurishkuro** [comment] 2017-06-16 02:39
* [ ] update documentation in `deployment.md`

**Comment by pavolloffay** [comment] 2017-07-04 12:33
Do you have any preference for the framework? What is the most used/mature one in Go? 

I found this https://github.com/go-swagger/go-swagger

**Comment by yurishkuro** [comment] 2017-07-04 15:01
When you say framework, it implies not just documenting but refactoring the endpoints to use that framework so that documentation and code are in sync. I'd agree swagger is the way to go. However, we first need to investigate how it will work with graphql, because we certainly need graphql to streamline interactions with UI. I don't know if graphql frameworks also help with auto documenting the API.

**Comment by pavolloffay** [comment] 2017-09-28 07:13
Related discussion https://groups.google.com/forum/#!topic/jaeger-tracing/L27aTD9kXRc

**Comment by yurishkuro** [comment] 2017-12-23 20:24
Duplicate of #456

**Closed by yurishkuro** 2017-12-23 20:24 UTC
Labels: documentation
