### ISSUE TITLE
Is it possible to start span on one server instance, and finish it on another?

### ISSUE THREAD

**Issue by veterr** [jaegertracing/jaeger#1415] opened 2019-03-10 09:12 UTC
Hi. I am using already Jaeger with HTTP requests, and I need to apply it with JMS MQ. For HTTP I use the approach shown in tutorial https://github.com/yurishkuro/opentracing-tutorial/tree/master/java , i.e.

try (Scope scope = Tracing.startServerSpan(tracer, httpHeaders, "format")) {

  // HTTP request/response

}

where scope = tracer.buildSpan(operationName).asChildOf(parentSpanCtx).startActive(true)

Is it possible to start the span on one server instance, and finish it on another? For example, if I send Jms message asynchronously. In the above example, I have the “scope” variable, and the scope.close() method is invoked automatically on leaving the try {} block. If I have the asynchronous MQ call it looks like I should somehow obtain the io.opentracing.Scope variable on the receiving side...

**Comment by yurishkuro** [comment] 2019-03-11 08:57
Jaeger span is designed to represent an operation in a process. In the producer that operation is writing to the queue, after which the operation ends. The consumer starts a new span, usually using follows-from reference type. This mode also supports multiple consumers.

Working example with Kafka: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter05

**Comment by veterr** [comment] 2019-03-13 15:21
Thank you for the example! Here consumer extracts the span context and builds the span as referenced from parent in startConsumerSpan method. But how the parent, i.e. producers context had been created? I.e. I did not see starting spans on the producer side, the message is just sent in ChatController.java

**Comment by yurishkuro** [comment] 2019-03-13 16:44
The Kafka client is instrumented/wrapped to create a span when writing.

**Comment by pavolloffay** [comment] 2020-07-14 11:43
I am closing this as this is tagged as a question and the conversation seems to be over.

**Closed by pavolloffay** 2020-07-14 11:43 UTC
Labels: question

**Comment by aneeskA** [comment] 2021-09-22 17:07
@yurishkuro I am trying to figure out this exact same problem using opentracing-go package. My strategy is this 1. create a parent span when the message is first read in the chain of consumers. Finish the parent span immediately after. (not exactly what I want, but this is good enough for now) 2. pass this parent span along with the message. 3. when any consumer reads the message, if a parent span is present, use that to create a child span. I use jaeger UI to collect the result. Everything shows up good.

<img width="867" alt="Screenshot 2021-09-22 at 10 33 04 PM" src="https://user-images.githubusercontent.com/514419/134389213-73a8cd3b-7221-49d4-9937-6f650ad3c98d.png">


So far so good. The problem is when I use elastic APM to display the same relationship. Elastic APM refuses to make the connection like Jaeger UI. What am I missing?


PS: I am closing the parent span in step 1 itself because I don't know how to pass the parent span to the last consumer. I know how to pass the span context around; but don';t know how to re-create the parent span from context so that I can call `span.Finish()` on it. Any idea what I am missing here?

**Comment by yurishkuro** [comment] 2021-09-22 17:30
> I know how to pass the span context around; but don';t know how to re-create the parent span from context 

Spans are not designed to represent work across service boundaries, each span must be started and finished in the same process. What you're doing already is the recommended approach.

I don't have any insights about Elastic APM.

**Comment by aneeskA** [comment] 2021-09-22 17:49
@yurishkuro Thank you for your quick response.  Looks like I am doing everything right; which is confirmed by Jaeger UI. Let me see if the elastic documentation has some helpful pointers.

**Comment by aneeskA** [comment] 2021-09-23 14:27
For anyone stumbling on this issue, Elastic APM added support for Jaeger tracing from v7.6 onwards. And my setup was using v7.5; thus the issue. Using the latest version of elastic stack on my local setup (using docker), I was able to see the same relationship as shown by Jaeger stack.
